### ISSUE TITLE
[Bug] Undefined lua_close simbol

### ISSUE THREAD

**Issue by T-bond** [blt4linux/blt4l#103]
Hello.

I am having trouble running blt4l with Payday 2.
I tried installing the latest release, and also my own builds. (Tried on local machine, and building in Docker with the same result)
Installation output:
https://pastebin.com/30QjKjD7

When running from console (because running from Steam, doesn't show any error, the game closes before start):
```
env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" ./payday2_release
dlHandle = 0x7ffb1232b150
03:53:37 PM Info: finding lua functions
03:53:37 PM Info: installing hooks
szCmd: /bin/sh -c '"/home/USERNAME/.steam/steam.sh" "steam://run/218620"' &
sh: symbol lookup error: ./libblt_loader.so: undefined symbol: lua_close
```

The Steam launch option is the same as I pasted to console, except the %command% part.
The libblt_loader.so is in place, as well as the mods folder. (Same as on repository)
Also tried manual building and copying the files, but got the same result.

I'm on Debian Sid (Bullseye).
Payday 2 version: 171
How can I solve this problem?

**Comment by dribbleondo** [comment]
Not sure why you'd omit the %command% from the command. That's there to give you a buffer to apply other, unrelated, commands via launch options. Try again, but with the %command% intact.

**Comment by T-bond** [comment]
It is in the Steam shortcut, I only replace when I run from the console to see the error.

**Comment by RomanHargrave** [comment]
I am not able to reproduce this.

Make sure these are, at a minimum, set:

```
SteamAppId=218620
SteamAppUser=<username>
SteamGameId=218620
suppress_restart=1
LD_PRELOAD=(path to libblt_loader.so)
```

My test scripts all run payday from its install directory, this may or may not make a difference, as payday two does not have any relative linkage (according to LDD, this doesnt stop it from runtime loading).

**Comment by T-bond** [comment]
I now compiled on my computer and I got the following error:
`symbol lookup error: ./libblt_loader.so: undefined symbol: lua_call`

@RomanHargrave  I don't know where I should set those values.

**Comment by T-bond** [comment]
It is solved now. Maybe there was some dependency error on sid.
