### ISSUE TITLE
erro while trying to make

### ISSUE THREAD

**Issue by biennaal** [blt4linux/blt4l#106]
guys Im getting the following error while making the project
$ make
[  6%] Building CXX object CMakeFiles/blt_loader.dir/src/event.cc.o
In file included from /home/bienna/blt4l/src/event.cc:1:
/home/bienna/blt4l/include/blt/event.hh:3:10: fatal error: 'deque' file not
      found
#include <deque>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/blt_loader.dir/build.make:76: CMakeFiles/blt_loader.dir/src/event.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/blt_loader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
Im using arch(i tried to install from aur but the links are outdated it gives error 404)

**Comment by RomanHargrave** [comment]
you are missing important C++ headers or your build environment is mis-configured.

**Comment by biennaal** [comment]
well apparently arch dont need/have that libraries so it doesnt have it on repositories, however if install libc++ from aur it solves the problems
