### ISSUE TITLE
Fails on Arch Linux

### ISSUE THREAD

**Issue by drewofdoom** [blt4linux/blt4l#11]
Would not build after cloning the repo. Build fails to find subhook.h despite it clearly being in the src directory. Did not pursue this strongly, however.

Installed using the release version 1.1 build 4. Had dep issues at first, but resolved those. One sticky issue is that /usr/lib{,32}/libssl.so.1.0.2 does not exist, despite the package version being at 1.0.2. The symlink to libssl.so is from a file called libssl.so.1.0.0. Manually symlinking to libssl.so.1.0.2 got rid of the libssl.so.1.0.2 error output when launching the game, but it still fails with the following output:

```
Game update: AppID 218620 "PAYDAY 2", ProcID 14847, IP 0.0.0.0:0
ERROR: ld.so: object '/home/drew/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/drew/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/drew/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
dlHandle = 0x7f4db37cd110
Game removed: AppID 218620 "PAYDAY 2", ProcID 14847 
No cached sticky mapping in ActivateActionSet.Installing breakpad exception handler for appid(steam)/version(1459463254)
```

Not much to go on, but hopefully we'll get this sorted.

**Comment by drewofdoom** [comment]
I was doing at least one thing incorrect: I did not put the full path in the Steam launcher. Adding the full path to libblt_loader.so resolved the launching issue. No mods show up, however. Still investigating.

One potential issue that may be keeping it from launching is that I have my Steam library on a secondary drive to keep from flooding my primary SSD with giant games. Does the loader assume that the path is base on "~/.local/share/Steam/steamapps/common/Payday 2"?

**Comment by Arvife** [comment]
I'm also on Arch, I had issues compiling too but replacing CMakeFiles.txt with the one from d677f766d89fb052d690f9eeb3100e06dbfd83fc solved it. Also, are you sure it's actually loading after putting the full path or is it just not loading it therefore launching the game fine?

**Comment by LeonardKoenig** [comment]
5ebc017012d9358945a074e0546408ba3ebe5d3d should fix the building issue, the directory was mistakenly removed from the include path in 55265b73e3871f4450db3965ab8ed0ea44483871.

I also have my game in a different path and I'm also running Arch, so neither should be the problem.
The symlink though is sadly required (for now).

My launch options are:  
`env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command% 2>&1 | tee /tmp/pd2.log`

Could you try using these and give us the `/tmp/pd2.log`?

Also the output of `ldd libblt_loader.so` could be useful.

**Comment by LeonardKoenig** [comment]
@RomanHargrave If you run Debian, could you please run `dpkg-query -L` on the openssl package? Possibly it also installs a `libssl.so.1.0.0`, so we could just link to this version for compatibility reasons (we'd need to use `:libssl.so.1.0.2` in the `target_link_libraries()`).

**Comment by BangL** [comment]
..and that's why i stopped using Arch. it's simply way too "bleeding edge" for daily usage.
everything fine on Manjaro ;)

**Comment by LeonardKoenig** [comment]
This has nothing to do with bleeding edge, tbh. It's just that they do not make a symlink to `libssl.so.1.0.2` ...

Manjaro is Arch with just repos leaking behind (potential security issues). I don't like it at all, though it has improved. Also usually Arch (and all Arch-based distros) break at some time. Most Manjaro users don't know how to fix their system -- and spam bbs.archlinux.org.

But don't turn this into a discussion about distros.

**Comment by BangL** [comment]
> Most Manjaro users don't know how to fix their system

i usually do, i just didnt want to have to it like every week. ^^

> But don't turn this into a discussion about distros. 

i didnt mean to, i just meant to report: i dont have this problem on manjaro.

**Comment by gvogets** [comment]
Wouldn't be the correct way to compile the releases against the libssl of the steam-runtime? They should be distribution-agnostic…

**Comment by LeonardKoenig** [comment]
@gvogets That's actually a good idea!

**Comment by LeonardKoenig** [comment]
I just pushed a new branch with a patch for enabling the install.sh on ArchLinux:
https://github.com/blt4linux/blt4l/tree/install_arch

@RomanHargrave Could you check whether this still works on non-Arch? ;-)

**Comment by RomanHargrave** [comment]
just woke up.

@LeonardKoenig  WRT libssl, debian ships the shared object as `libssl.so` in `libssl-dev` for whatever reason. `ldconfig` is linking `libssl.so.1.0.2` to that. You can safely link `libssl.so.1.0.0`, as `ldconfig` also symlinks `libssl.so` to that.

@LeonardKoenig Your changes to the build script are detecting packages as uninstalled for me. I'll fix that.

@gvogets I'm actually working on that. I was going to use a SteamOS VM or Container, but that's been a bit of a mess, so I'm going to see about setting up a chroot.

**Comment by LeonardKoenig** [comment]
Good morning! :)

So I broke it *yay*

I just changed the CMakeLists.txt to a `find_package()` mechanism, but we still could just change it the way I said of course.

I think linking via steam_runtime shouldn't be such a big issue, especially not on Debian. Just download the steam_runtime and it'll set up toolchain + chroot for you.

**Comment by LeonardKoenig** [comment]
@BangL Is it possible that you talked about the source and not about the pre-built release when saying that it'd work on Manjaro?

Because the openssl package is *exactly* the same on both:
```
tar tvf openssl-1.0.2.g-3-x86_64.pkg.tar.xz| grep libssl
lrwxrwxrwx root/root         0 2016-03-02 18:16 usr/lib/libssl.so -> libssl.so.1.0.0
-r-xr-xr-x root/root    512560 2016-03-02 18:16 usr/lib/libssl.so.1.0.0
-rw-r--r-- root/root       284 2016-03-02 18:16 usr/lib/pkgconfig/libssl.pc
```

**Comment by RomanHargrave** [comment]
@LeonardKoenig ugh. these steam repos are slow.

**Comment by BangL** [comment]
> Is it possible that you talked about the source and not about the pre-built release when saying that it'd work on Manjaro?

yes. i build from source. sry if that was misleading.

**Comment by RomanHargrave** [comment]
@LeonardKoenig finally got around to looking at `install.sh`. It looks like you left a negation in place. Removed it and it's working fine. Merged in to master. Finish up any work you had on arch_install so we can delete the branch.

**Comment by drewofdoom** [comment]
I was able to successfully build and install the mod using the install_arch branch. Mods loading now.

**Comment by LeonardKoenig** [comment]
Fixes merged, branch deleted. I'll close this as solved!

**Comment by SuperNascher** [comment]
The game crashes on my machine too, but there was no error messages during the build process.

The output from the launch option above:

`ERROR: ld.so: object '/home/kevin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kevin/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/mnt/Games/Linux/Steam/steamapps/common/PAYDAY 2/payday2_release: /home/kevin/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by ./libblt_loader.so)
`

**Comment by BangL** [comment]
@SuperNascher 
try the steamrt build.

**Comment by SuperNascher** [comment]
@BangL Ok, thanks.
