### ISSUE TITLE
BLT4L keeps the game from starting

### ISSUE THREAD

**Issue by Mikasu-X14** [blt4linux/blt4l#110]
I wanted to get some mods(obviously) for my game on Ubuntu 18.04 but BLT4L doesn't work. I tried using Ubuntu precise SteamRT version, Debian and few older versions, each of them doesn't work. My game would simply shutdown as fast as it started. Besides, the install.sh script never worked and I had to apply some fixes to the framework.sh script to make it work since the Steam Library wasn't pointed out correctly in my case. Even with the fixed scripts, the loader doesn't work, my Payday 2 only starts without the arguments.

**Comment by dribbleondo** [comment]
You need to manually compile BLT4L, as pre-builts were not designed with Bionic in mind. This is due to OpenSSL changing between version 3 to 4, and which both SuperBLT and regular BLT4Linux cannot find it.

**Comment by Mikasu-X14** [comment]
I tried to compile it but OpenSSL seems to be, indeed, the problem. I'll compile it just to get the log so you can give me more help on how to do that.

**Comment by dribbleondo** [comment]
I would advise @RomanHargrave to make another prebuilt for Bionic as Bionic's OpenSSL is screwing up newer builds. When I get back onto Linux, i'll look through my Bash history to work out how I myself fixed the Openssl issue

**Comment by Mikasu-X14** [comment]
Thank you and here is the build log https://pastebin.com/1rAeTX2J
Also, here are the lines I changed in framework.sh
``${STEAM_BASE:=${STEAM_BASE:~$HOME/.steam/steam} } 2>/dev/null
   ${STEAM_LIBRARY:=$STEAM_BASE/steamapps/} 2>/dev/null``
between line 50 and line 54.

**Comment by KingBowser** [comment]
I'll set up a chroot and do that

**Comment by RomanHargrave** [comment]
@Dribbleondlo I'll look in to setting up a chroot

**Comment by Mikasu-X14** [comment]
by the way, my edits on the framework.sh are the fix for the issue #80, since it was also a problem for me though I got around it by fixing the STEAM_LIBRARY variable that wasn't pointing at the good directory.

**Comment by Mikasu-X14** [comment]
I progressed into the compiling issue, I can now do cmake but now I'm searching for the next step's issue. By the way, for compiling under Ubuntu, we need libssl-dev package installed to have the OpenSSL library and the SSL Crypto library

**Comment by Mikasu-X14** [comment]
Got a successful build after deleting what was in the build directory and restarting the compiling process. Now I'll test to see if that build works or not

**Comment by Mikasu-X14** [comment]
Successful, completely working BLT4L. I would suggest to add the libssl-dev package to the readme for Ubuntu users. Thanks a lot for the loader guys :D
