### ISSUE TITLE
Missing information in the readme for Ubuntu

### ISSUE THREAD

**Issue by Mikasu-X14** [blt4linux/blt4l#111]
I have no problems with BLT4L at the moment but as I suggested, and I am suggesting this again just to be sure you saw that, libssl-dev should be added to the list of dependencies for Ubuntu.  That fixed my problem with compiling BLT4L on bionic. I don't know for which versions of Ubuntu the precompiled version is but you told me it wasn't meant for bionic at the moment. So to help other Ubuntu 18.04 users with that issue, I think it could be useful to add a simple line in the readme that will say "libssl-dev (for newer version of Ubuntu)" or something similiar.

**Comment by RomanHargrave** [comment]
The issue is with bionic I think. I've been dragging my feet on making setting up a chroot to build it in, but can devote some time tonight to doing that.
