### ISSUE TITLE
issue when running make

### ISSUE THREAD

**Issue by unlimitedcoder2** [blt4linux/blt4l#112]
alex@alex-desktop:/blt4l/build$ make
[  6%] Linking CXX shared library libblt_loader.so
/usr/bin/ld: cannot find -lc++abi
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/blt_loader.dir/build.make:460: recipe for target 'libblt_loader.so' failed
make[2]: *** [libblt_loader.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blt_loader.dir/all' failed
make[1]: *** [CMakeFiles/blt_loader.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
alex@alex-desktop:~/blt4l/build$

I have been unable to fix this issue. Anybody know how to fix it?

**Comment by RomanHargrave** [comment]
You are missing the standard C++ library, presumably.
