### ISSUE TITLE
Nothing happened

### ISSUE THREAD

**Issue by sTiKyt** [blt4linux/blt4l#115]
1.Downloaded package blt4l using AUR
2.Set launch option to blt4l %command%
3.Then i launched the game (Where nothing changed)
4.Left game and placed WolfHUD into new generated "mods" folder
5.Nothing!
When i launch game i don't have any new menus, any new info, just nothing!

**Comment by BangL** [comment]
this project is obsolete, use SuperBLT instead.

**Comment by BangL** [comment]
https://gitlab.com/znixian/payday2-superblt#gnulinux

**Comment by sTiKyt** [comment]
Did it already, forgot to close issue..
