### ISSUE TITLE
Payday dont open

### ISSUE THREAD

**Issue by kasumo-spec** [blt4linux/blt4l#116]
![Captura de tela de 2021-02-24 02-43-49](https://user-images.githubusercontent.com/71528151/108953743-735c0500-764a-11eb-8617-0e76020bb1cd.png)
![Captura de tela de 2021-02-24 02-44-13](https://user-images.githubusercontent.com/71528151/108953750-7525c880-764a-11eb-97a9-616ea51dcc2f.png)

I have installed everything, but when i try to start, dont run. Without the Launch Options, the game run normally. Can help me?

**Comment by dribbleondo** [comment]
Yeah, BLT4L is not worth using anymore unless you have a good reason to (I removed it from my guide for a reason).
