### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#12]
We should probably put together a webpage. For this we have a few options:
- GitHub pages - we put the site in a repo and host it at GH Pages
- I host it - meh
- We talk to James about getting a page on paydaymods.

GH Pages would be great because it's the simplest solution and we have collaboration. I can do the same for hosting myself, but it really doesn't offer advantages as I'm also still HTML-Only, much like GH Pages.

With the paydaymods option we don't really have control over our listing, I would assume.

@ZNixian I know that you had some thoughts on this. Would you mind sharing some ideas?

**Comment by LeonardKoenig** [comment]
I don't know whether GH-Pages are free as webhosts or only free domain but I think collaborating with paydaymods would anyway be a good idea -- we don't want to make installing mods on Linux/Windows too different. This of course doesn't in any way mean that we can't have a BLT4L website.

But regarding webdev + hosting stuff I'm basically the wrong person to ask :-)

**Comment by RomanHargrave** [comment]
GH Pages are free hosting and domain at *.github.io, but I can CNAME from blt.hargrave.info or something if we want. *.pw domains are 10/yr or something like that, but it's not really in my budget right now as I already foot the bill for three domains.

**Comment by LeonardKoenig** [comment]
Ah, that's nice. I think gh-pages would fill the bill

**Comment by RomanHargrave** [comment]
Pinging at @JamesWilko WRT paydaymods.com listing.

also sent an email.

**Comment by ZNixian** [comment]
Hello,
I can offer hosting on a dedicated server, on a LAMP stack. Also, if there are any additional PHP libraries etc, then I can install them. Also, I can host email, if that would be useful.

**Comment by RomanHargrave** [comment]
@ZNixian not sure that we will ever need CGI support, but if we needed it, it would be great if there were an Alternative to PHP.

**Comment by ZNixian** [comment]
@RomanHargrave If you have something in mind (eg, nodejs) then I can install it. I can also provide SSL certs.

**Comment by RomanHargrave** [comment]
Just recieved correspondence from @JamesWilko. Looks like a listing on paydaymods is incoming.

**Comment by polarathene** [comment]
Definitely get listed on paydaymods at least. I perhaps didn't use the best keywords in google but had to hop through a few pages to find this repo(didn't remember the name). So improving discoverability would be great :)

For hosting you also have the option of Heroku I think, you're able to run node js and deliver web content for free there, they have a good reputation with web devs :) I'd just go with the github pages approach if it's able to handle what you need.

**Comment by RomanHargrave** [comment]
@polarathene @JamesWilko I've been trying to get listed and had a running email convo with James, but haven't gotten a response.

**Comment by dribbleondo** [comment]
Very late to the party, I know, but it may be worth posting it to the Payday 2 section of [ModWorkshop](https://modworkshop.net/), to increase it's visibility.

**Comment by ZNixian** [comment]
@dribbleondo It's probably not really worth it, as anyone who has used BLT and has moved to GNU+Linux will quickly find it. In fact, the top 3 DuckDuckGo results for 'payday 2 mods linux' are about BLT4L.

**Comment by dribbleondo** [comment]
Yeah, That's true. The only reason I suggest that, is that at least it'll have a "website" or a portal.

**Comment by ZNixian** [comment]
If someone wants to quickly put together a static website, then I'd be more than happy to host it and pay for a domain name. @RomanHargrave Any thoughts on that?

**Comment by RomanHargrave** [comment]
Sure. There was some talk with the folks at pdmods/mod workshop about adding a section, but it never materialized.

**Comment by ZNixian** [comment]
Would you have a problems/thoughts/ideas if | were to quickly build a small website, and host it?

**Comment by RomanHargrave** [comment]
no, just try to be lightweight/light on js

**Comment by ZNixian** [comment]
That work fine, given that I usually have NoScript turned on for that exact reason.

**Comment by ZNixian** [comment]
I've got blt4linux.info, and set up a GitHub webhook to automatically pull from https://github.com/ZNixian/blt4linux.info

Now, time to write the HTML...

**Comment by dribbleondo** [comment]
I can make a Logo for the site if need be, may as well contribute something =)

**Comment by ZNixian** [comment]
A logo would be good, and some ideas for the styling. Here's what I've got so far: http://blt4linux.info/

TLS is on it's way, just waiting for the DNS to update (24 hour TTL default by my registrar, unfortunately) so Let's Encrypt starts working.

**Comment by dribbleondo** [comment]
Here's the logo I have made (resize as you wish) http://imgur.com/a/ucHBH

If need be, I can remove the text so that the penguin takes up the most space

**Comment by ZNixian** [comment]
Oh, nice. Maybe if you could make one without the penguin for the favicon (icon on the tab bar), and leave that one up, maybe for use as the main icon?

Also, could you please use a transparent background - it makes it a bit easier to put on a textured background, and works better as a favicon. Thanks

**Comment by dribbleondo** [comment]
I did use a transparent background. Here are the direct links:  http://i.imgur.com/EgJBa7y.png for big
http://i.imgur.com/cEbQGDJ.png for small

**Comment by ZNixian** [comment]
Nice. I'll add the favicon in a minute, but I'll need to figure out where to put the big icon. Any ideas?

**Comment by ZNixian** [comment]
The favicon needs to be perfectly square. Could you change that quickly?

**Comment by dribbleondo** [comment]
It's now 300x300: http://imgur.com/7bQ7HVn.png

**Comment by ZNixian** [comment]
1: Oh, thanks. BTW the icon version is missing the penguin - is that intentional?

2: Personally, the icon on the side looks a little too big, though your judgement on that is probably better than mine.

Anyway, I'll put that icon on there as soon as I'm done writing the next part of the installation thing.

PS: Should we have one of those big 'fork on GitHub' buttons, a (prominent) link in the footer, or something in the 'About' area. What's your opinon?

**Comment by dribbleondo** [comment]
1. I removed the prenguin because the favicon is less than 50x50. You're not gonna see the penguin.

2.  When the About section is added, the logo can be moved to the "install" segment, so it looks less weird.

3. You can if you want, i'm not gonna stop ya =P

**Comment by ZNixian** [comment]
I tried it with the penguin, and it doesn't look too bad: http://i.imgur.com/jMROEDo.png
Anyway, I'll go and try it without the penguin, and link that

**Comment by ZNixian** [comment]
Looks about the same, minus the penguin: http://i.imgur.com/PNMH4uv.png

**Comment by polarathene** [comment]
@ZNixian is it ok to use ES6 JS in the browser like that? Not sure how long ago native support has been available, though I guess with FF and Chrome it'd be pretty widespread for most users desktop/mobile?

Any reason you're not going the usual markdown/github-pages way? Sorts out nice aesthetics with the colours/typography themes provide. Updating is as easy as updating the markdown then..

> That work fine, given that I usually have NoScript turned on for that exact reason.

Anyone visiting the site with NoScript on would not be able to use the tabs you've setup due to JS you're using to switch?

**Comment by ZNixian** [comment]
1. http://caniuse.com/#search=let
2. SSL, for a start (although I'm currently waiting for the DNS cache at Let's Encrypt to expire). Also, if we ever want to do anything dynamic, it would be a bit easier. It's also easy to just copy across the colours. Ultimately, we could switch to Jekyll and use one of their themes.
3. I've been working on a seperate set of headers that are hidden by JS. While the tabs would not work, all the parts of the list would still be visible.

In fact, I might see if I can find a theme that would work and copy the instructions across.

**Comment by polarathene** [comment]
1. Ah good to know! :)
2. [GH-Pages supports SSL?](https://virgil3d.github.io/)
3. Great :) I personally don't see much reason to cater to disabled JS beyond just avoiding tabs. Is there a statistic for users that still do this?

**Comment by ZNixian** [comment]
1. GitHub Pages supports SSL for .github.io sites, but I'm pretty sure it doesn't for anything else.
2. I've had a quick look, and can't find any statistics.

**Comment by dribbleondo** [comment]
The Steam command for the binary release is "env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command% -skip_intro" (-skip_intro is optional, but useful for incredibly obvious reasons.)

**Comment by ZNixian** [comment]
I'll put that on once I'm done trying out Jekyll

**Comment by polarathene** [comment]
I use this steam command on Arch/Manjaro:

```
LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so /usr/lib/libcurl-compat.so.4.4.0" %command% > /tmp/pd2.log 2>&1
```

Not sure if the libcurl lib needs to be there still, I remember it not working without having that there thouogh. The part of `%command%` is for outputting anything logged by PD2 to a file, also helps pickup on problems like the libcurl one was for me before.

**Comment by dribbleondo** [comment]
I see you've changed the layout of the site again....

**Comment by ZNixian** [comment]
Okay, the repo now behaves like a GitHub pages repo - as in, any changes you make get applied within a few seconds. index.md is the main file, where everything goes.

**Comment by polarathene** [comment]
Nice. It's a bit narrow, the container width you set should be wider? 780px avoids forcing the horizontal scrollbars on content.

Will you be including an LD_PRELOAD example, or some pictures/gif on adding the command in steam?  May want to add a note that Arch users may need the additional load of libcurl like I did. 

Not a fan of the bullet list style being outside personally.

`list-style: disc inside none;` or if you'd like to center the bullets vertically, `list-style: none;` and custom bullet like so:

```
ul li:before {
			content:"";
			display:inline-block;
			background-color: #333;
			border-radius: 50%;

			width: 5px;
			height: 5px;
			transform: translate(-140%,-60%);
		}
```

**Comment by ZNixian** [comment]
I've done the two CSS based things, I'll go and add in the LD_PRELOAD thing now

**Comment by RomanHargrave** [comment]
> Will you be including an LD_PRELOAD example, or some pictures/gif on adding the command in steam

If we're going to mention that, you should point out that the installers (both from source, and packages) will set that for you, if they can find steam.

**Comment by RomanHargrave** [comment]
As for the download placeholder, 

you could link the latest release page: https://github.com/blt4linux/blt4l/releases/latest

and there may be a way to link the files for individual download on github using a serverside script.

**Comment by ZNixian** [comment]
1. I'll be sure to mention that. I knew that the installer did that, but not the AUR packages.

2. Already done that.
`Go to the [GitHub release page](https://github.com/blt4linux/blt4l/releases/latest)`

3. I could probably do a script, after everything else is done.

**Comment by RomanHargrave** [comment]
> but not the AUR packages.

I'm referring to the builds/packages posted on the release page.

Who maintains the AUR packages? They should probably look in to doing it as a post-install script (but touching things in user directories is weird from a packaging perspective).

Also, last time I checked (some time ago), the AUR packages were really outdated. I flagged them, so hopefully that's been sorted out.

**Comment by ZNixian** [comment]
Oh, somehow I didn't notice that the binaries came with a installer script. Will fix those instructions.

**Comment by RomanHargrave** [comment]
@ZNixian I invited you to the BLT org. We could move the website in to the org, if you want (it's up to you).

**Comment by ZNixian** [comment]
@RomanHargrave Ok, thanks. I've moved it across.

**Comment by ZNixian** [comment]
I put in a stub of a bit about LD_PRELOAD, TODO finish it.

**Comment by polarathene** [comment]
> If we're going to mention that, you should point out that the installers (both from source, and packages) will set that for you, if they can find steam.

That's neat, will it add the libcurl dependency if needed to the steam command like I needed? My steam library lives on another partition instead of in my home, not sure if the script would figure that out or not if that's where the command gets added.

**Comment by ZNixian** [comment]
@polarathene If the libray isn't in the default place, IDK how the script handles it.

**Comment by RomanHargrave** [comment]
> If the libray isn't in the default place, IDK how the script handles it.

The user has to set STEAM_LIBRARY

**Comment by RomanHargrave** [comment]
@ZNixian here's the current BLT logo if you want to use it: [svg](http://paste.qc.to/cbIqx1tMxY?mime=image/svg) and [png](http://paste.qc.to/DNOnD2hd5p?mime=image/png)

**Comment by ZNixian** [comment]
@RomanHargrave After transfering ownership of the repo, I've had some trouble with getting the auto-updates working on my server. Mind transferring the repo back?
PS: I've added the new favicon.

**Comment by ZNixian** [comment]
@RomanHargrave After transfering ownership of the repo, I've had some trouble with getting the auto-updates working on my server. Mind transferring the repo back?
PS: I've added the new favicon.

**Comment by dribbleondo** [comment]
I want to make a correction to the info about Beardlib on the site. Beardlib is compatible, but anything that requires loading truly custom assets (custom heists/ Beardlib music module etc.) will not work as it uses sysFS, responsible for loading the assets, something which Overkill has yet to add. Beardlibs lua functionality does work, as I have a Beardlib mod which works under Linux (Rain on all heists for those curious).

**Comment by ZNixian** [comment]
@dribbleondo Make a pull request. Once it's merged, the changes should automatically be applied to the live website. Assuming, of course, that my system is feeling tolerant - it seems a little broken after moving to the blt4linux group.

**Comment by RomanHargrave** [comment]
@ZNixian yeah, I can transfer the repo back. What exact trouble are you having, though? Are you using pages or something else?

**Comment by ZNixian** [comment]
A custom script I wrote to update it from GitHub.

**Comment by RomanHargrave** [comment]
Does it use git hooks? Or the github API?

**Comment by ZNixian** [comment]
Currently, the GitHub API.

**Comment by RomanHargrave** [comment]
> What's the PHP script look like?

I'll transfer it back, but now you've got me curious

**Comment by ZNixian** [comment]
It's pretty much a smear of PHP, bash, C, and a Ruby script. I'm working on simplifying it a bit, though.

**Comment by polarathene** [comment]
@ZNixian What does it need to do? I can set you up with a simple nodeJS app that access the markdown via rawgithub and parses the markdown to return html as output? Sounds a bit convulted to span all those languages to accomplish it :|

**Comment by ZNixian** [comment]
I'm currently rewriting it to clean it up a bit. You'd need to run Jekyll to build the site, otherwise I'd probably have used something like that.

**Comment by polarathene** [comment]
What's Jekyll doing in particular that is special compared to other markdown parsers? I've not used it before.

**Comment by ZNixian** [comment]
It has a template system, and it's used by the GitHub pages template I was using.

**Comment by RomanHargrave** [comment]
You should look at what I'm doing for hargrave.info - https://github.com/RomanHargrave/website

It's similar, but it works by having a shared key that travis uses to decrypt the deployment script.

**Comment by ZNixian** [comment]
I'll have a look at that, it seems like a interesting way to do it

**Comment by ZNixian** [comment]
Okay, it should be working properly now. I'll get round to packaging up the code I used for it at some point.

**Comment by ZNixian** [comment]
@RomanHargrave The basic architecture is now PHP (don't ask) -> shell script to set environment variables -> setuid program that runs 'git pull' and 'jekyll build'
