### ISSUE TITLE
Windows-specific paths in mods

### ISSUE THREAD

**Issue by drewofdoom** [blt4linux/blt4l#13]
While testing this out, it looks like there are some case sensitivity issues.

HoloHUD, for example, is badly done. Filenames are a mixture of upper and lower case, but all of the calls in the LUA scripts are for lower-case names.

I doubt that this is something that can be fixed in the hook itself. More likely will have to direct users to a solution using ciopfs for compatibility: http://www.brain-dump.org/projects/ciopfs/

PocoHUD is also only partially working. Not sure if this is due to case sensitivity or something else.

`Err: Failed to load mods/PocoHud3/poco/../poco/3rdPartyLibrary.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3_class.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3_Options.luacErr: Failed to load mods/PocoHud3/poco/../poco/Hud3.luacPoco:Init`

From browsing through the PocoHud code this appears to be a separate issue, as the filenames seem to be called correctly. I will set up ciopfs locally and test when I have some more time later today or tomorrow.

**Comment by RomanHargrave** [comment]
Thanks Windows _(TM)_.

CIOPFS seems like a pretty good idea, but I think that it would be more user-friendly if we just fix the mods and open PR's to the authors to accept the changes. It is after all the author of the mods problem for expecting `fileA` to match `FILEa`. That's just bad practice.

**Comment by RomanHargrave** [comment]
I'm looking at the HoloHud source, and it looks like it also expects `mod_overrides` to work. This does not work in the linux client (along with voice chat), and Overkill have yet to bother with fixing it.

**Comment by drewofdoom** [comment]
That explains why Enhanced Hitmarkers also spits out errors about copying files.

Though, oddly, EH actually works despite all the errors and expecting the textures to live in mod_overrides.

I agree that we should send upstream bug reports for individual mods. Hopefully most devs will accept the requests, but for those who don't, it may be worth noting in the README that CIOPFS may be a workaround for troublesome modes.

Still have not tested it over here, but given that HoloHUD is the most problematic mod and won't work anyways due to `mod_overrides`, I may just have to fake it by manually changing a few file names on some mods that _are_ working properly...

**Comment by RomanHargrave** [comment]
I got HoloHud working.

**Comment by RomanHargrave** [comment]
Tutoro/HoloHud#1 fixes this.

**Comment by RomanHargrave** [comment]
Interesting. Getting a black screen at mission briefing.

**Comment by vincent-t** [comment]
I fixed enhanched hitmarkers. In menumager.lua change functions to:
```
function EnhancedHitmarkers:IsTextureOverridden(texture)
	local file=io.open(self.override_path .. texture, "r")

	if file~=nil then
		io.close(file)
		return true
	else
		return false	
	end
end
```
also change:
```
function EnhancedHitmarkers:InitializeModOverridesFolder()
	local overrides = file.GetFiles(self.override_path)

	if not overrides then
		log("[EH] Creating Enhanced Hitmarkers overrides folder...")
		file.CreateDirectory(self.override_path)
		overrides = file.GetFiles(self.override_path)
	end
```
Last step implement ```CreateDirectory``` in blt:
```
int luaF_createDirectory(lua_State* L)
{
	size_t len;
	const char* directory = lua_tolstring_orig(L, 1, &len);
	bool success = Util::EnsurePathWritable(directory);
	lua_pushboolean_orig(L, success);
	return 1;
}
```

**Comment by RomanHargrave** [comment]
Our equivalent of `luaF_CreatedDirectory` already exists and is mapped to the same LUA function as in Windows.

**Comment by RomanHargrave** [comment]
Please test your fixes to Enhanced Hitmarkers at commit 04c28b41a89b18efff31cecb00d890df7c32fccf and let me know if that works.

If it does, I can release an update when I get home (my blasted workstation decided not to autoconnect to my network, so I can't do it remotely >.<).

**Comment by BangL** [comment]
tested with r10 real quick..

ok first.. for my test, i changed
`	if not overrides then`
to
`	if not next(overrides) then`
because if the folder isnt existant, we still get an empty table from `file.GetFiles`. so checking for nil is not enough.

next:
`file.CreateDirectory` IS creating a directory, but the permissions are fucked up:
`drw-r-xr-x 2 bangl users 4,0K 2016-04-13, 19:46:29   'Enhanced Hitmarkers'/`
..since the owner doesnt get the executable bit, the function cant continue creating the subfolders for now.
however, when i fix the permissions manually, and restart the game a few times it works in the end.

**Comment by RomanHargrave** [comment]
That's not distro specific, it was a bad decision I made late at night setting the permission mask.

**Comment by vincent-t** [comment]
It is now working with blt4l. Here is the updated Enhanced Hitmarkers:
[Enhanced Hitmarkers.tar.gz](https://github.com/blt4linux/blt4l/files/218746/Enhanced.Hitmarkers.tar.gz)

**Comment by BangL** [comment]
just contacted TdlQ (Enhanced Hitmakers) to inform him about this, so let's wait a bit before we make another repo for this or something like that. Maybe we can get into his official version, that would be the best solution.

**Comment by RomanHargrave** [comment]
I was going to suggest that @vincent-t open a PR to the repo.

**Comment by BangL** [comment]
yeah that was my first thought as well, but i think there is no repo, thats the problem^^

**Comment by RomanHargrave** [comment]
Marking wontfix, because BLT4L can't fix this, and leaving open for further discussion.

**Comment by RomanHargrave** [comment]
Closing as it's not a prevalent issue, and wontfix.
