### ISSUE TITLE
steamrt compatibility

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#14]
I've been working on getting a build working for Ubuntu 12.04 LTS + SteamRT. Unfortunately, steamrt does not ship a cURL that supports the `CURLOPT_XFERINFO_` options, which are currently at the center of HTTP support in BLT4L. We should find a way to work around this.

**Comment by RomanHargrave** [comment]
also, I dare anyone reading this to find anything worthwhile when searching for `cURL` without excluding `PHP` from their search. good god.

**Comment by RomanHargrave** [comment]
OK. PHP excluded. 

It looks like XFERINFO is the successor of PROGRESSFUNCTION. I'll see if I can work with this.

**Comment by RomanHargrave** [comment]
building on steamrt image. lgtm.

**Comment by BangL** [comment]
how exactly do you build against the steamrt?
just by changing the ld paths before calling make, or by chrooting?

**Comment by RomanHargrave** [comment]
I have a bunch of chroots for builds, and a fish script that uses schroot to execute a packaging build in each one.

Don't use the steamrt setup script though. That thing sucks. Would suggest setting up an ubuntu precise repo, adding the steam repos, and grabbing what you need, which is what the script does, though in typical valve style, it does it in a spectacularly bad manner that makes an incredible mess.
