### ISSUE TITLE
Can't get BLT working

### ISSUE THREAD

**Issue by snverse** [blt4linux/blt4l#15]
I'm running Mint 17.1-64 bit and I'm trying to get BLT running. I'm new but I got the most versed Linux user I know and he couldn't get it either. We tried the pre-compiled BLT4L versions of Ubuntu-Precise-steamrt and Ubuntu-trusty. My friend didn't know if those files were compiled for 64 or 32-bit so we tried to compile the libblt_loader.so ourselves, both with the install.sh and manually. We didn't have any luck in getting the game to run with any of those libblt_loader.so.

Whenever I try to launch payday, it brings up the "Preparing to launch payday 2" window and then it quickly closes. We went through everything we could think of and managed to throw some weird errors, CPU level errors, and somehow inject payday 2 into steam and crash the application. I have no clue what to do at this point.

EDIT: I got it working with the libblt_loader.so that I compiled. No idea why it worked and didn't before.

**Comment by LeonardKoenig** [comment]
Can it be closed then now? Otherwise it might be useful if you can provide logs.

**Comment by RomanHargrave** [comment]
Closing. Will reopen if @snverse can provide information about what happened.
