### ISSUE TITLE
file.GetFiles making the game unresponsive

### ISSUE THREAD

**Issue by GreatBigBushyBeard** [blt4linux/blt4l#18]
OS: Linux Mint 17.3 Cinnamon
blt4l Version: 1.1-r8_Ubuntu-precise-steamrt

When loading into a heist it gets stuck as it errors out when attempting to execute many mod lua files, which executed fine when loading into the menu.

This pastebin should include the entire list of mods that are being loaded and the error list. These errors only show when loading into a heist, I can load into the menu just fine and all the mods, including the ones that error in the shown log work.

**Comment by RomanHargrave** [comment]
That's strange. Could you archive a copy of your mods folder and post it here, please?

**Comment by GreatBigBushyBeard** [comment]
I just tested a fresh mods folder and it works fine, so It must be a mod which I'm not sure how that works. But it is.

**Comment by GreatBigBushyBeard** [comment]
Seems there is an issue in BeardLib, not completely sure on what it is due to the lack of helpful errors in the console.

**Comment by GreatBigBushyBeard** [comment]
I've found it, the issue is in file.GetFiles. Just calling it sends the game into the entire loop that I reported.

**Comment by RomanHargrave** [comment]
Interesting. I'll look in to it when I get home.

**Comment by RomanHargrave** [comment]
@GreatBigBushyBeard can you please point me to the file/line in BeardMod where you found this to cause problems so that I can use it as a test case to fix this?

**Comment by GreatBigBushyBeard** [comment]
@RomanHargrave This line, https://github.com/GreatBigBushyBeard/PAYDAY-2-BeardLib/blob/dev/mods/BeardLib/BeardLibCore.lua#L191

It is mainly to do with the mod_overrides folder, so you'll probably need one for testing it.

**Comment by RomanHargrave** [comment]
Out of curiosity, is `mod_overrides` working for you?

How about voice chat?

Neither are BLT-related issues, but nonetheless, I have them, and overkill has been of little help.

**Comment by GreatBigBushyBeard** [comment]
It does not work for me, if you're wondering what BeardLib is doing with it, it loads any Script Data files in mod_overrides and replaces them when they are requested by the PackageManager:script_data func.

I haven't tried voice chat yet, but I'll try and test it if I can remember.

Regarding the mod_overrides folder, I contact Overkill today about the issue, but I haven't got a reply back yet.

For future reference, I've got my Payday setup using symbolic links to connect my assets and mods folder between my Linux and Windows install. It's unlikely that it will be relevant to the issue at hand, but anything is possible.

**Comment by BangL** [comment]
mod_overrides isnt actually "broken". it's not even meant to be working on linux yet.

**Comment by GreatBigBushyBeard** [comment]
@BangL Elaborate

**Comment by BangL** [comment]
there isnt even a "mods" entry in the menu.
pretty sure its just overkill's lazyness though.

**Comment by GreatBigBushyBeard** [comment]
@BangL I'm fairly certain it only appears when mod_override mods are installed.

**Comment by BangL** [comment]
..oh well that actually makes sense. i'm taking it back then.. might be just broken then.

**Comment by BangL** [comment]
well... the bundles are the same on linux, so the lua code must be the same as well.
i just grep'ed the pd2 lua code recursively and case insensitive and there is not a single occurrence of "mod_override"... so its part of the binary, which is pretty much the only difference on linux..

however, when i grep the linux-binary for "mod_overrides", there are actually 7 occurrences.

so yea. seems broken, you're right.

**Comment by GreatBigBushyBeard** [comment]
@BangL I doubt Overkill would have tested it before release, considering they don't really use mods and the feature was kinda just shoved in. Hopefully we can get it resolved soon though.

And yes, the mod_override stuff is engine side. As far as I remember the lua code gets the mods by DB:mods(), and there are a few functions engine side which handle the mod_overrides.

**Comment by RomanHargrave** [comment]
@BangL I poked at the application binary and it appears that `mod_overrides` is handled that way. There are several namespaces and functions that refer to it.

**Comment by RomanHargrave** [comment]
OK. Granted I have not tested this at runtime, it looks like `list_files` the underlying implementation of `getdirectory` was leaking a `DIR*` stream. I've fixed that at commit c4c896235f51338efd839d63d42544152b8fff5f. Let me know if that changes any behaviour, for better or worse.

**Comment by BangL** [comment]
..uhm what?
i think we have a misunderstanding here. i don't need push right's at all, overkill needs to fix it.

**Comment by BangL** [comment]
oh well, okay. seems legit.

**Comment by RomanHargrave** [comment]
I would have messaged you, if it weren't for the fact that GH does not support messaging.

**Comment by GreatBigBushyBeard** [comment]
@RomanHargrave I just built the current repository and it appears that the file.GetFiles issue has been fixed.
