### ISSUE TITLE
Have install.sh modify the games launch properties automatically

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#19]
This is an improvement suggestion/request. To anyone that has the constitution to work with VDF (I personally would not touch it with a very, very, long stick).

We should enable install.sh to modify `localconfig.vdf` and set `LaunchOptions` under `21860` to `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%`.

The modification should be as cross-machine friendly as possible, and thus needs to make _no assumptions_ about the end users PC. For this reason, I would suggest Perl 5.x as a scripting utility for this because it is more robust than Bash, and is installed on nearly every distribution conceived by mankind since the creation of life, the universe, and everything.

For best results, we would need to parse the VDF data in to a inspectable structure, change the value, and emit the modified file.

**Comment by LeonardKoenig** [comment]
Hm, the relevant file is
`~/local/share/Steam/userdata/$SOMEID/config/localconfig.vdf`

where `$SOMEID` seems not to be the SteamID. But what should we do if multiple users are on the PC? Modify them .vdf's all?  
Also I could imagine steam resetting them on login/logout ie. not allowing anyone else to modify these -- but I have not tested.

Also there might already be settings that shouldn't be overridden. I think this is easy enough for anyone to figure out (hopefully)

**Comment by RomanHargrave** [comment]
Personally, I think that the best course of action is to modify it for all accounts, as while there can be multiple steam data profiles under one steam prefix, it is pretty much not going to be the case if there is a separate computer user for each steam user (as would be the case in a family PC, or friends-over-gaming PC), since each user would have their own steam prefix.

**Comment by RomanHargrave** [comment]
Fixed by 5e99fd37112d08909d94a09cd43cd8c1c818eb27
