### ISSUE TITLE
Issue with file.DirectoryExists

### ISSUE THREAD

**Issue by GreatBigBushyBeard** [blt4linux/blt4l#25]
I'm unable to get file.DirectoryExists to ever return true for any directories that exist in the PAYDAY 2 directory. 

Executing this line should always return true/positive, but it doesn't (for me atleast)
``` lua
log(tostring(file.DirectoryExists("./mods/")))
```

**Comment by RomanHargrave** [comment]
LUA Truth is non-zero (though it's not documented), so there shouldn't be a problem there since C++ boolean types are non-zero true also.

**Comment by RomanHargrave** [comment]
Can't reproduce this. Is this occurring for every version?

**Comment by GreatBigBushyBeard** [comment]
I re-installed the blt4l_1.2_Ubuntu-precise-steamrt version and it appears to be working now, I'm not sure what the issue was before.
