### ISSUE TITLE
cURL-GNUTLS incompatibilities 

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#30]
Been having issues with builds using cURL-GNUTLS lately due to `CRYPTO_numlocks` not being defined.

**Comment by theo546** [comment]
Got this bug too, "home/theo546/.local/share/Steam/steamapps/common/PAYDAY 2/payday2_release: symbol lookup error: /usr/lib/blt4l/libblt_loader_steamrt.so: undefined symbol: CRYPTO_num_locks"

**Comment by RomanHargrave** [comment]
Use curl4-openssl-dev.

I need to make the build script fail with GNUTLS
