### ISSUE TITLE
Crashes immediately on Slackware64-current

### ISSUE THREAD

**Issue by Aerol** [blt4linux/blt4l#31]
I've read through some of the other issues and they were all "fixed", but they were lucky enough to have things magically fixed or patched. :/

> dlHandle = 0x7f2f12220168
> 06:02:08 AM Info: finding lua functions
> 06:02:08 AM Info: installing hooks
> Setting breakpad minidump AppID = 218620
> Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198142119173 [API loaded no]
> Game removed: AppID 218620 "PAYDAY 2", ProcID 18635
> No cached sticky mapping in ActivateActionSet.

I've seen people pasting stack traces, and I'll be happy to, as soon as someone call tell me how.

I've tried using 1.2r1 prebuilt for Debian Stretch, but no difference, used latest git and compiled, and tried 1.2r1 snapshot source.

Output of ldd onlibblt_loader.so

> ```
>    linux-vdso.so.1 (0x00007ffc1649c000)
>    libdl.so.2 => /lib64/libdl.so.2 (0x00007f4cb835a000)
>    libcurl.so.4 => /usr/lib64/libcurl.so.4 (0x00007f4cb80ea000)
>    libz.so.1 => /lib64/libz.so.1 (0x00007f4cb7ed2000)
>    libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f4cb7b52000)
>    libm.so.6 => /lib64/libm.so.6 (0x00007f4cb7842000)
>    libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f4cb762a000)
>    libc.so.6 => /lib64/libc.so.6 (0x00007f4cb725a000)
>    /lib64/ld-linux-x86-64.so.2 (0x000055a2af942000)
>    libidn.so.11 => /usr/lib64/libidn.so.11 (0x00007f4cb7022000)
>    libssh2.so.1 => /usr/lib64/libssh2.so.1 (0x00007f4cb6df2000)
>    libssl.so.1 => /lib64/libssl.so.1 (0x00007f4cb6b7a000)
>    libcrypto.so.1 => /lib64/libcrypto.so.1 (0x00007f4cb672a000)
>    liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007f4cb651a000)
>    libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00007f4cb62ca000)
>    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4cb60aa000)
>    libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007f4cb5e8a000)
> ```

I'm at a loss, so any help anybody can provide is greatly appreciated.

**Comment by Ozymandias117** [comment]
Just to verify, I assume you are able to launch Payday without the BLT hook? I see a lot of issues around related to "No cached sticky mapping in ActivateActionSet." in steam in general.

For a backtrace, you can either enable coredumps, or run the game with GDB attached.

Here is the procedure I use for running with GDB attached:
```
cd '/path/to/steamapps/common/Payday 2/'
gdb ./payday2_release
```

You will now be entering gdb commands:
```
set environment LD_PRELOAD=./libblt_loader.so
set environment SteamAppId=218620
run
```

When it crashes, you can get a backtrace with:
`bt`


Assuming Slackware doesn't use systemd's coredumpctl yet, this should allow you to get a coredump:
Close steam
`ulimit -c unlimited && steam`
Run Payday from Steam

There should now be a core file in steamapps/common/PAYDAY 2 which can be examined with:
`gdb --core=./core ./payday2_release`

**Comment by Aerol** [comment]
Kinda weird but I can and can't run PD2 without the BLT hook; if I run ./payday2_release when Steam isn't running it will start steam and the game runs fine, if I have Steam open and try and run PD2 it crashes the same without the 2 info lines from BLT.

If I run payday2_release in gdb, I get
>Starting program: /home/aerol/.local/share/Steam/steamapps/common/PAYDAY 2/payday2_release
>dlHandle = 0x7ffff7ffe168
>lua_call wasn't found in dlHandle, won't load!
>[Thread debugging using libthread_db enabled]
>Using host libthread_db library "/lib64/libthread_db.so.1".
>dlHandle = 0x7ffff7ffe168
>05:10:50 PM Info: finding lua functions
>05:10:50 PM Info: installing hooks
>[New Thread 0x7fffea67e700 (LWP 2933)]
>[New Thread 0x7fffdf30f700 (LWP 2934)]
>szCmd: /bin/sh -c '"/home/aerol/.local/share/Steam/steam.sh" "steam://run/218620"' &
>sh: symbol lookup error: ./libblt_loader.so: undefined symbol: pthread_create
>[Thread 0x7fffdf30f700 (LWP 2934) exited]
>[Thread 0x7fffea67e700 (LWP 2933) exited]
>[Inferior 1 (process 2932) exited normally]

**Comment by Ozymandias117** [comment]
Well, the ldd output certainly doesn't have libpthread, so I can understand why it can't find pthread_create. ;P

Now the question is, how did you get a build without libpthread... How did you go about building libblt_loader?

**Comment by Aerol** [comment]
Just ran ./install.sh and copied the "env LD_..." string in place

**Comment by RomanHargrave** [comment]
That's odd. pthread is a dependency and _should_ be specified in the compiler params.

**Comment by Aerol** [comment]
As a test/workaround I added /lib64/libpthread.so.0 to LD_PRELOAD and I get http://vpaste.net/yo2e4 from gdb

I just checked ldd on your own libblt_loader.so from blt4l_1.2-r1_Ubuntu-precise-steamrt.tar.xz and there's no mention of libpthread, and I searched through all the files in the repo and there's no mention of pthread anywhere (other than binary matches in the various compiled files)

Where exactly is pthread being specified to be linked in?

**Comment by Aerol** [comment]
OK, so I dunno what the hell is up with my system, but if I take the prebuilt binary it loads in and seems to work just fine, game starts and I get a BLT update message thing and mods menu under Options, with or without having libpthread.so.0 in LD_PRELOAD.

**Comment by RomanHargrave** [comment]
This all could be due to the fact that there is an ABI or library difference between your system and the Steam RT. You may be better off just running with the SteamRT binary.

**Comment by Ozymandias117** [comment]
You could try running payday with the broken shared object with the following:
LD_DEBUG=symbols LD_PRELOAD=./libblt_loader.so ./payday2_release

It should at least tell us where it's looking for pthread and unable to find it. Probably it will just confirm Roman's suspicions.

**Comment by Aerol** [comment]
[132mb dump](https://www.dropbox.com/s/aahuhlv0uoe37qp/debug?dl=0) of stderr and stdout from
```LD_DEBUG=symbols LD_PRELOAD=./libblt_loader.so ./paday2_release```
using locally compiled libblt_loader.so.

Did a couple grep's of pthread_create and libpthread, didn't find anything that jumped out at me, but dunno what to really look for.

**Comment by Ozymandias117** [comment]
The symbols that are failing there are completely different... Was this a run with Steam already open that you said failed regardless of the BLT hook? It looks like it's X11 extensions that it can't find...

```
21038: /usr/lib64/libX11.so.6: error: symbol lookup error: undefined symbol: XextAddDisplay (fatal)
21038: /usr/lib64/libX11.so.6: error: symbol lookup error: undefined symbol: _XextAddDisplay (fatal)
21038: /usr/lib64/libX11.so.6: error: symbol lookup error: undefined symbol: XextCreateExtension (fatal)
21038: /usr/lib64/libX11.so.6: error: symbol lookup error: undefined symbol: _XextCreateExtension (fatal)
```

**Comment by Aerol** [comment]
Ran without Steam running.

I just did the same with and without steam running and grep'd for "undefined" with nothing but the same X11 extension stuff. Same output with the prebuilt libblt_loader.so

**Comment by RomanHargrave** [comment]
@Aerol if you have solved the problem, please provide a solution and close the issue, otherwise I will close this as abandoned in a few days.
