### ISSUE TITLE
Can't Find Dependencies on Arch Linux

### ISSUE THREAD

**Issue by Grimmoire** [blt4linux/blt4l#33]
Apologies for raising the bug count since this is probably user error

```
ERROR: ld.so: object '/home/grimmoire/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/grimmoire/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/grimmoire/Storage/SteamLibrary/steamapps/common/PAYDAY 2/payday2_release: /home/grimmoire/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /home/grimmoire/Packages/blt4l/build/libblt_loader.so)
/home/grimmoire/Storage/SteamLibrary/steamapps/common/PAYDAY 2/payday2_release: /home/grimmoire/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/grimmoire/Packages/blt4l/build/libblt_loader.so)
/home/grimmoire/Storage/SteamLibrary/steamapps/common/PAYDAY 2/payday2_release: /home/grimmoire/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/grimmoire/Packages/blt4l/b
```

**Comment by awilliamson** [comment]
Not had this error myself. I'm on Arch Linux too.

But http://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx may be of help?

**Comment by RomanHargrave** [comment]
How did you build this? 

I know there's an AUR package for it, but did you build it your self, or get it prebuilt?

If you built it yourself, your LD path is messed up and the linker can't find the libraries you linked it against. If you used a copy here, you don't have the same library versions as the corresponding target distribution.

**Comment by Grimmoire** [comment]
I tried the AUR package first then built it manually to see if that might fix it

```
$ ldd /home/grimmoire/Packages/blt4l/build/libblt_loader.so
	linux-vdso.so.1 (0x00007ffc8f3d4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f56b4de2000)
	libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f56b4b6a000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f56b4952000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f56b45ca000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f56b42c2000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f56b40aa000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f56b3d0a000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x000055b6b115d000)
	libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f56b3ad2000)
	libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f56b38a2000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f56b362a000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f56b31b2000)
	libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f56b2f62000)
	libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f56b2c7a000)
	libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f56b2a42000)
	libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f56b283a000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f56b261a000)
	libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f56b240a000)
	libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f56b2202000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f56b1fea000)
```

**Comment by RomanHargrave** [comment]
And both failed?

It looks like steam is overwriting LD_PATH. You could try the steamrt version, or symlink the needed libraries in to steamrt's lib folder.

**Comment by Grimmoire** [comment]
Yeah, both behaved the same. I took @awilliamson's advice and changed my path. The game now launches, albeit without blt4l. Here's the log I get now
```
ERROR: ld.so: object '/home/grimmoire/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Setting breakpad minidump AppID = 218620
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198025196635 [API loaded no]
```

**Comment by awilliamson** [comment]
@Grimmoire I remember something similar when I used a package. So I built it myself direct from Github, and it managed to work. Did you make sure to set the launch command parameters for the game? Sorry I can't be much more help, it's been a while since I encountered these problems.

**Comment by Grimmoire** [comment]
it's currently built manually from github. launch paramaters are
`env LD_PRELOAD="$LD_PRELOAD /home/grimmoire/Packages/blt4l/build/libblt_loader.so" %command% | tee /tmp/pd2.log `

**Comment by RomanHargrave** [comment]
please try putting in the same folder as the binary. though it shouldn't affect anything, that's what the installer does, so it would possibly benefit us, since it looks like the preloader is skipping your binary.

Is it possible that you don't have the Lua sources installed?

**Comment by Grimmoire** [comment]
i put libblt_loader.so in the payday 2 game folder and changed the preload path and the log is still the same (i'm assuming that's the binary you're referring to). the lua base is installed

**Comment by RomanHargrave** [comment]
This is just odd. Check `dmesg` while you launch PD2 to see if SELinux or similar is preventing the preload.

**Comment by luck3y** [comment]
@Grimmoire That looks like what was happening to me, the hook loaded and the mod lua was there but it wasn't found. What filesystem are you using?

**Comment by Grimmoire** [comment]
```
[268611.393701] payday2_release[18425]: segfault at 10 ip 00000000007ea0ee sp 00007ffecfc38f40 error 4 in payday2_release[400000+12bb000]
[268683.043190] payday2_release[19224]: segfault at 10 ip 00000000007ea0ee sp 00007fffe2c78090 error 4 in payday2_release[400000+12bb000]
[268805.350103] payday2_release[20508]: segfault at 10 ip 00000000007ea0ee sp 00007ffc3695ffb0 error 4 in payday2_release[400000+12bb000]
[305564.522234] usb 1-1.3: USB disconnect, device number 7
[512490.139626] traps: payday2_release[21381] general protection ip:7f3c05ae5750 sp:7ffd99adc2e8 error:0 in libc-2.24.so[7f3c059ba000+195000]
```
@luck3y i'm using btrfs

**Comment by luck3y** [comment]
@Grimmoire I bet its the same issue as me. Try building the version from master and see if that fixes it.

**Comment by Grimmoire** [comment]
i am built from the master

**Comment by luck3y** [comment]
Oh, I misread, you're not even getting the hook loaded.

**Comment by RomanHargrave** [comment]
@Grimmoire I noticed that there are some segfaults in your dmesg output. I know you got the game running without BLT loading, though...

**Comment by polarathene** [comment]
@Grimmoire Hey, I'm an Arch user too(also just recently chose to use XFS with a new system so thanks @luck3y for solving that :) ). I've followed through the discussions here and the problem seems to be due to `libcurl` not supporting `CURL_OPENSSL_3` with the newer packages. If you have `lib32-libcurl-compat` installed this addresses that problem. Try see what versions you have with `ls -l /usr/lib/libcurl*`

For me I just had to add the compat version to the preload like this:
`LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so /usr/lib/libcurl-compat.so.4.4.0" %command%`

If you're having any other issues, such as with `libstdc++.so.6`, are you using native arch libs instead of the ubuntu ones for steam? Look up Arch Wiki article, there is an AUR package steam-native/steam-libs, I think that I used to avoid updates breaking Steam.

**Comment by LeonardKoenig** [comment]
Hi, I'm back from holidays and just tested -- may it be that you use steam with the steam runtime while building blt4l against the native runtime?

The combinations that should work are:

 - steam with native runtime & blt4l AUR package or self-built from git against native libs
 - steam with SteamRT & prebuilt steamrt releases / built against steamrt as described in Valve's docs

Did you try these and did it work?

**Comment by RomanHargrave** [comment]
@Grimmoire is your issue resolved?

**Comment by LouisLoudogTrottier** [comment]
Anyone on Fedora can take a look at this, Yesterday i had bunch of problem but this made the install smooth. Might help my fellow penguins. <(") https://github.com/blt4linux/blt4l/issues/50

**Comment by RomanHargrave** [comment]
Closing unresolved(?)
