### ISSUE TITLE
Loads but mods don't seem to work?

### ISSUE THREAD

**Issue by luck3y** [blt4linux/blt4l#35]
First of all, thanks for making this, PD2 on Linux is a really great game, and it's awesome that the Linux community can get mods working.

I'm using Fedora 23, and selinux is disabled.

If I use either self-built or steamos hook, I seem to get the same behaviour:

11:48:19 PM Info: installing BLT LUA API
11:48:19 PM Info: Loading BLT Base
11:48:19 PM Info: luaL_loadfile() = 0
11:48:19 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
11:48:19 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
11:48:19 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
11:48:19 PM Lua: [Mods] Loading mods for state (table: 0x2997b140)
11:48:19 PM Info: lua_pcall(...) = 0

Starting PD2 with:

LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command% > /tmp/pd2.log 2>&1

I have the base lua copied from the distribution in my ~/.steam/steam/steamapps/common/PAYDAY 2/mods directory, so I don't really know why this isn't working (I don't have a mods option under options). I also have PocoHud3 in there. Any clues? 

I though originally perhaps it was because of the space in "PAYDAY 2", so I set LD_LIBRARY_PATH to the path of the installed game, then set LD_PRELOAD=libblt_loader.so and that behaved the same way.

**Comment by RomanHargrave** [comment]
did you make sure that the structure of the mods folder is correct?

**Comment by luck3y** [comment]
Yeah, well, I think so. I have mods/ then everything copied from the dist there, like this:

PAYDAY 2/
  base/
  downloads/
  logs/
  PocoHud3/
  saves

I see all of the dist files in base.

**Comment by luck3y** [comment]
Sorry that should say:

PAYDYAY 2/
       mods/
          [rest of listed files & does]

**Comment by luck3y** [comment]
I guess I should just figure out where it tries to load the base .lua files from and go from there eh ;)

**Comment by RomanHargrave** [comment]
I don't follow.

The reason I asked is that if BLT doesn't find its mod runtime, It'll just not load it. How did you install the mods folder? If you unpacked it from the zip file or cloned the lua repository in to a mods folder, you should be fine...

**Comment by luck3y** [comment]
Sorry if I wasn't clear. I took the mods folder that came with the steamos tarball, and moved it into my PAYDAY 2 folder.

**Comment by RomanHargrave** [comment]
And that's all thats in the BLT log?

**Comment by luck3y** [comment]
Yeah, just those few lines repeated over and over.

**Comment by RomanHargrave** [comment]
Can you send me an untouched tarball of your mods folder?

**Comment by luck3y** [comment]
OK, I'll upload it and link here. BTW, I just rechecked the logs on startup, heres the full thing (I must have missed this the first time).

`
ERROR: ld.so: object '/home/kwills/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
dlHandle = 0x7ff14037e148
01:29:39 PM Info: finding lua functions
01:29:39 PM Info: installing hooks
Setting breakpad minidump AppID = 218620
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197968435011 [API loaded no]
01:29:39 PM Info: installing BLT LUA API
01:29:39 PM Info: Loading BLT Base
01:29:39 PM Info: luaL_loadfile() = 0
01:29:39 PM Info: lua_pcall(...) = 0
01:29:48 PM Info: installing BLT LUA API
01:29:48 PM Info: Loading BLT Base
01:29:48 PM Info: luaL_loadfile() = 0
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
01:29:48 PM Lua: [Mods] Loading mods for state (table: 0x7ff1401aa9c0)
01:29:48 PM Info: lua_pcall(...) = 0
01:29:48 PM Info: installing BLT LUA API
01:29:48 PM Info: Loading BLT Base
01:29:48 PM Info: luaL_loadfile() = 0
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_manager.txt', no data loaded...
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_keybinds.txt', no data loaded...
01:29:48 PM Lua: [Warning] Could not load file 'mods/saves/mod_updates.txt', no data loaded...
01:29:48 PM Lua: [Mods] Loading mods for state (table: 0x7ff1401a8400)
01:29:48 PM Info: lua_pcall(...) = 0
`

**Comment by luck3y** [comment]
So its an issue with the Steam gameoverlayrenderer.so possibly?

**Comment by luck3y** [comment]
Mods folder tarball here: https://drive.google.com/open?id=0By27Rb27OVeYanppeTRQV2wweGM

**Comment by RomanHargrave** [comment]
No, that's just because steam puts both the 32-Bit and 64-Bit overlay in the preload list.

I'll check this tarball out a little later.

**Comment by luck3y** [comment]
I tracked this down to dirent having DT_UNKNOWN returned from XFS, quick fix is to just treat it the same way you're doing DT_LNK, patch below. Let me know if want a PR and I'll send one, but this fixes the issues for me :)

diff --git a/src/fs.cc b/src/fs.cc
index d458294..a1968e7 100644
--- a/src/fs.cc
+++ b/src/fs.cc
@@ -44,7 +44,7 @@ namespace blt {
                 {
                     bool isDir;
                     {
-                        if(next->d_type == DT_LNK)
+                        if(next->d_type == DT_LNK || next->d_type == DT_UNKNOWN)
                         {
                             char current_path[PATH_MAX + 1];
                             snprintf(current_path, PATH_MAX, "%s/%s", path.c_str(), next->d_name);

**Comment by luck3y** [comment]
Wow, that's terrible formatting, I'll just send up a PR.
