### ISSUE TITLE
libblt_loader

### ISSUE THREAD

**Issue by troll-senin** [blt4linux/blt4l#38]
Hi, i've downloaded the loader, run install.sh,no errors. a folder installer_build is made, containing folder cmakefiles and cmakecache.txt and that's about it, there's no libblt_loader.so, and also the lua folder is empty. Can you help me? Thanks

**Comment by RomanHargrave** [comment]
The installer should have put it in your `PAYDAY 2 ` folder. Check there - it's usually under `$HOME/.steam/steam/steamapps/common/PAYDAY 2`. If you have python installed, the latest installer revision should also have configured steam for you.

**Comment by troll-senin** [comment]
I have python installed. In the PAYDAY 2 folder the only folder is Assets and the files context.xml, dieselx.cfg, game.ver, libopenal.so.1, libsteam_api.so, payday2_release. I have linux mint. I compiled and tried to install it manually, i didn't got any errors, but it doesn't work.

**Comment by pt300** [comment]
Could you provide output from build?

**Comment by troll-senin** [comment]
Unfortunately i can't right now, but with the one i downloaded i think some files are missing and in the installer.sh some paths are missing or altered

**Comment by pt300** [comment]
Have you cloned the repository with git client or have you obtained it in other way?

**Comment by troll-senin** [comment]
Both, neither worked

**Comment by pt300** [comment]
could you tell me how exactly have you tried compiling it?

**Comment by troll-senin** [comment]
Followed the instructions on the page, but that's not the issue, the problem is with the files, i saw that the installer on here has been updated 9 days ago, maybe it doesn't do what its supposed to. Everything is updated, everything works fine, it just doesn't create libblt_loader.so. Like i said before some folders are empty, and after i run the installer in terminal or just run, nothing happens to them, so i think somebody played with them. Can any of you compile or download and run blt4l and test it?

**Comment by pt300** [comment]
I haven't tried the script but beside it everything works fine

**Comment by pt300** [comment]
It would be really helpful if you could provide output from the build script because right now nobody can help you

**Comment by troll-senin** [comment]
When i'll get home, i will post the output

**Comment by RomanHargrave** [comment]
The script just runs a build which outputs the object. IIRC it _moves_ it to the payday folder rather than copying it. And unless you have the Lua base installed the loader will have nothing to load and the game will start normally.

**Comment by troll-senin** [comment]
I recompiled it again and it worked, but now when i update the payday2 blt hook it gets stuck on extracting the archive.

**Comment by RomanHargrave** [comment]
The hook updater is part of the lua and won't do anything useful on linux.

**Comment by troll-senin** [comment]
Ok then,everything works, thanks for the help, i will close the thread. Thanks for the help.
