### ISSUE TITLE
how to set `LD_PRELOAD` for the PAYDAY2 process

### ISSUE THREAD

**Issue by Novian3002** [blt4linux/blt4l#41]
First of I am sorry if this is the wrong place, just delete this if you want.

I have absolutley no Idea how to set `LD_PRELOAD` for the PAYDAY2 process, could you maybe explain that a bit better in the readme?

**Comment by LeonardKoenig** [comment]
Go to Steam and right-click the game. Go to "properties" (should be the
last entry of the context menu iirc) and then hit "Launch options" or
similar.
In the text field put:

```
LD_PRELOAD=/path/to/library %command%
```

That should do it.

**Comment by Novian3002** [comment]
with the launch option "LD_PRELOAD=/home/sven/Downloads/blt4l-master/build/libblt_loader.so %command%" my game doesnt start anymore. 
It doesnt crash or anything it just doesnt show up.

**Comment by Vild** [comment]
I have to use `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so /lib/libcurl.so.4 /lib/libstdc++.so.6" %command%`.
This is because I linked the blt_loader.so to a newer libcurl and libstdc++ than what payday uses.

**Comment by LeonardKoenig** [comment]
Just to be sure the launch option shouldn't be quoted.

If you didn't, then the game not launching is the primary issue. As you
don't have a space in your path it's probably some version mismatch or
similar.

Could you append ` > /tmp/blt.log 2>&1`
to the command line, launch the game, and then post the content of the
'/tmp/blt.log' file?

**Comment by Novian3002** [comment]
```
dlHandle = 0x7f4f90009168
/home/sven/.steam/steam/steamapps/common/PAYDAY 2/payday2_release: relocation error: /home/sven/Downloads/blt4l-master/build/libblt_loader.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

Here it is

**Comment by Vild** [comment]
@Novian3002 What distro are you using?
Did you try my launch command?

**Comment by Novian3002** [comment]
@Vild Linux Mint 18, it launches with your command but the mod i pasted into my payday 2 folder (pocohud) doesnt seem to work.

**Comment by LeonardKoenig** [comment]
Yep, there's version mismatch, Dans command should help.

Now that it's launching, but the mod doesn't work (what mod?) can you give
us the output of the blt.log file (You need to append what I wrote earlier
again) now?

**Comment by LeonardKoenig** [comment]
Pocohud should work, it did for me last time I tested. Be sure to download
the clubsandwih version.

**Comment by Novian3002** [comment]
@LeonardKoenig I tried to install PocoHud, but I am not even sure if I did it right.
Where do I have to put the mod files? I just put them under lua/mods but the instructions seem to say that I have to "copy a lua mod base" to my payday 2 folder. 
Can anybody clarify what I have to do?

**Comment by LeonardKoenig** [comment]
the subfolder mods in the directory lua of your download should go into the
Payday 2 root dir.
Within the mods folder should he the PocoHud3 dir that includes the mod.txt.

Eg:

```
PAYDAY 2/
|- mods/
     |- PocoHud3/
         |- mod.txt
  |- ...
```

On Nov 13, 2016 17:06, "Novian3002" <notifications@github.com> wrote:

@LeonardKoenig <https://github.com/LeonardKoenig> I tried to install
PocoHud, but I am not even sure if I did it right.
Where do I have to put the mod files? I just put them under lua/mods but
the instructions seem to say that I have to "copy a lua mod base" to my
payday 2 folder.
Can anybody clarify what I have to do?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/blt4linux/blt4l/issues/41#issuecomment-260194902>, or mute
the thread

**Comment by Novian3002** [comment]
@LeonardKoenig If i put the mods system link into my PAYDAY 2 dir it breaks, can I just make a new folder called mods and drag my PocoHud3 in there?

**Comment by LeonardKoenig** [comment]
You can just create a new folder mods with the contents of lua/mods. Alternatively use symlinks:

```
$ cd "/path/to/PAYDAY 2"
$ ln -s /path/to/blt4l/lua/mods $PWD/mods
```
Then put PocoHud3 folder into mods/ dir in PAYDAY 2

**Comment by Vild** [comment]
Isn't it better to copy the folder?
Like the install script does https://github.com/blt4linux/blt4l/blob/master/install.sh#L155

**Comment by Novian3002** [comment]
The weird part is my symlink to mods is broken even in the lua folder, the mods folder in Payday-2-BLT-Lua doesnt exist

**Comment by Vild** [comment]
have you done `git submodule init; git submodule update`?

**Comment by Novian3002** [comment]
@Vild No I didnt because I got an error message but I assumed just downloading the subhook files ( because these were missing) would work.

**Comment by LeonardKoenig** [comment]
@Vild Depends on what you want. For most copying is better, especially if you want to download, install and then delete the original contents. I prefer symlinking though.

@Novian3002 You have downloaded the archive, right and didn't clone the repo, right?
Clone the repo with submodules

**Comment by LeonardKoenig** [comment]
Alternatively download a binary release.

**Comment by Novian3002** [comment]
Yeah I just cloned it and installed it that way and dragged the mods folder (now with files in it) to my PAYDAY 2 directory, I dragged PocoHud3 into it but it still doesnt seem to work (hud doesnt show up ingame).

**Comment by Novian3002** [comment]
I dont even get the ingame options which normally come with Btl

**Comment by LeonardKoenig** [comment]
So the structure should be:

```
PAYDAY 2/
 |- mods/
    |- PocoHud3/
       |- mod.txt
 |- ...
```

And the launch options:
```
env LD_PRELOAD="$LD_PRELOAD /path/to/blt4l/build/libblt_loader.so  /lib/libcurl.so.4 /lib/libstdc++.so.6" %command% > /tmp/blt.log 2>&1
```

After launching with this, what's the content of `/tmp/blt.log`?

**Comment by Novian3002** [comment]
I can confirm that the structure and the launch options
Output of blt log:
`ERROR: ld.so: object '/home/sven/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sven/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/path/to/blt4l/build/libblt_loader.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/libcurl.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Setting breakpad minidump AppID = 218620
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561197992192367 [API loaded no]`

**Comment by Vild** [comment]
You need to change the `/path/to/blt4l/build/libblt_loader.so` to where your `libbtl_loader.so` is.
also change the `lib/libcurl.so.4 /lib/libstdc++.so.6` part. I guess for you they would be in /usr/lib instead of /usr

**Comment by Novian3002** [comment]
@Vild thats why I deleted my comment I realized that myself

**Comment by Vild** [comment]
oh, It didn't update on my screen :p

**Comment by Novian3002** [comment]
I am using the right path now  (i think) `env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /lib/libcurl.so.4 /lib/libstdc++.so.6" %command% > /tmp/blt.log 2>&1`
but I still get an error
`ERROR: ld.so: object '/home/sven/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/sven/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/lib/libcurl.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/lib/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
dlHandle = 0x7feaa1799168
/home/sven/.steam/steam/steamapps/common/PAYDAY 2/payday2_release: relocation error: /home/sven/Downloads/blt4l/build/libblt_loader.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference`

**Comment by Novian3002** [comment]
Okay I think I found the problem I cant find the right place to link 
`env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /usr/lib/libcurl.so.4 /usr/lib/libstdc++.so.6" %command% > /tmp/blt.log 2>&1`  doesnt work because the libstdc++ and libcurl arent in that folder, I tried searching for them and found them both in diffrent folders. Linking to them like this`env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/i386-linux-gnu/libstdc++.so.6" %command% > /tmp/blt.log 2>&1` 
Also didnt work. Are the files supposed to be in their respective folders?

**Comment by LeonardKoenig** [comment]
Please use blockquotes for this, otherwise it's barely readible ;)

What's the content of the logfile when using the second command?

**Comment by Novian3002** [comment]
How do I blockquote

**Comment by LeonardKoenig** [comment]
fencing with triple backticks instead of single

**Comment by Novian3002** [comment]
There we go

**Comment by Novian3002** [comment]
Which second command do you mean?

**Comment by LeonardKoenig** [comment]
It's more likely that not SSL is the issue but you using the 32-bit version of libstc++, use this instead:

```
env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64--linux-gnu/libstdc++.so.6" %command% > /tmp/blt.log 2>&1
```

Note I changed the `i386` to `x86_64`.

**Comment by Novian3002** [comment]
```libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/x86_64-linux-gnu/libcurl.so.4)```

```env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/libstdc++.so.6" %command% > /tmp/blt.log 2>&1```

**Comment by LeonardKoenig** [comment]
Then try adding ssl to the bunch, too:

```
env LD_PRELOAD="$LD_PRELOAD /home/sven/Downloads/blt4l/build/libblt_loader.so  /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0" %command% > /tmp/blt.log 2>&1
```

But we also provide release builds, you could just use eg.
https://github.com/blt4linux/blt4l/releases/download/1.2-r3/blt4l_1.2-r3_Ubuntu-precise-steamrt.tar.xz

**Comment by Novian3002** [comment]
WE DID IT LADS, the release build and the included launch option worked for me. 
Thanks for all the patience!

**Comment by LeonardKoenig** [comment]
Nice, that what these builds are for ;)
