### ISSUE TITLE
fs_delete_dir is broken, plus suggestions

### ISSUE THREAD

**Issue by Ozymandias117** [blt4linux/blt4l#42]
I went to pull up and noticed the addition of fs_delete_dir...

if (currentNode->d_name == "." || currentNode->d_name == "..") is comparing two c-style strings, so you're only comparing a memory address. Also shouldn't return after removing the first file on 188.

Not actually sure how that hasn't wiped anyone's hard drive yet... I just wiped mine while trying to figure out how it hasn't already happened...
I would suggest this implementation, which seems less error prone than just fixing that function: https://stackoverflow.com/questions/3184445/how-to-clear-directory-contents-in-c-on-linux-basically-i-want-to-do-rm-rf/3184915#3184915

Can I also suggest we get rid of -fpermissive in the CMake script? We should probably really use -Wall -Werror and fix the bugs that the compiler already knows about...

Another thing I noticed on this branch is that SubHook is crashing whenever we go down to the "won't load" branch in blt_main, since we have statically initialized SubHooks, and the destructor in the subhook submodule doesn't verify the hook exists before dereferencing in the destructor.

Finally, why do we have the threadList in http.cc? Why not just create the threads and detach them? We're never rejoining, anyway...

Wanted to at least open a discussion before just making some of those changes.

**Comment by RomanHargrave** [comment]
I'm a bit busy with school at the moment, but you are welcome to open a PR to fix it. I'll see about getting around to it tomorrow.

**Comment by Ozymandias117** [comment]
Pushed the changes for threads and delete_directory.
Haven't tested the changes to zip.cc enough to add be able to start building with -Wall/-Wextra yet.

**Comment by RomanHargrave** [comment]
@Ozymandias117 Those two commits on lgtm at first glance, ran some updates. 

WRT "the changes to zip.cc" could you perhaps keep them available in a feature branch so that I can look at them until you are ready to merge them? I'm going to go ahead and run the builds for binary dist.

**Comment by RomanHargrave** [comment]
Closing fixed.
