### ISSUE TITLE
symbol std::__cxx11::basic_string…, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6

### ISSUE THREAD

**Issue by johndrinkwater** [blt4linux/blt4l#44]
Had this issue after compiling from source —on Ubuntu 15.10—, 
```
payday2_release: relocation error:  /home/john/code/blt4l/build/libblt_loader.so: symbol
_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3_,
version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```
Resolved it by defining `-D_GLIBCXX_USE_CXX11_ABI=0` in CMakeLists.txt
Not posting as a PR because I don’t know full ramifications for users on other distros..

**Comment by RomanHargrave** [comment]
This typically happens when your compiler attempts to link a different version of a library than it compiled a an object for. At least, if I recall correctly.
