### ISSUE TITLE
libblt_loader.so error

### ISSUE THREAD

**Issue by sysadam** [blt4linux/blt4l#45]
I get this when running `sh install.sh` both with sudo and without.

`Checking for libcurl4-openssl-dev`
`Checking for zlib1g-dev`
`Checking for cmake`
`Checking for build-essential`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/bogdan/Downloads/blt4l/installer_build`
`[100%] Built target blt_loader`
`Looking for payday2_release... this could take a moment`
`cp: ‘/home/bogdan/Downloads/blt4l/installer_build/libblt_loader.so’ and ‘./libblt_loader.so’ are the same file`
`Traceback (most recent call last):`
`  File "/home/me/Downloads/blt4l/installer/enable_blt_wrapper.py", line 13, in <module>`
`    vdf.kv['UserLocalConfigStore']['Software']['Valve']['Steam']['apps']['218620']['LaunchOptions'] = 'env LD_PRELOAD=\\"$LD_PRELOAD ./libblt_loader.so\\" %command%'`
`KeyError: 'apps'`
`Launch parameters for PAYDAY 2 on all your Steam Profiles have been set to load BLT`

**Comment by marco-sciuto** [comment]
I ran into the same issue time ago.
I think I managed to solve the first part (regarding the 'cp') by adding a / after $STEAM_LIBRARY
`PD2_DATA=$(dirname "$(find $STEAM_LIBRARY/ -maxdepth 4 -type f -name payday2_release)")`
I think that the script needs some improvements since the dirname returns . when the folder is not found.

I did not investigate further on the python part.

Tested on Ubuntu 16.04

**Comment by sysadam** [comment]
Still getting the same error.

**Comment by marco-sciuto** [comment]
Which error? Do you still have this?
`cp: ‘/home/bogdan/Downloads/blt4l/installer_build/libblt_loader.so’ and ‘./libblt_loader.so’ are the same file`

My fix is only for this part, not for the last.

**Comment by sysadam** [comment]
Yes, that one still shows. Nothing in the error message has changed.

**Comment by RomanHargrave** [comment]
This is happening because the location of PAYDAY 2 (apparently) is resolved to `.`:

`install.sh:140`
```sh
echo "Looking for payday2_release... this could take a moment"
PD2_DATA=$(dirname "$(find $STEAM_LIBRARY -maxdepth 4 -type f -name payday2_release)")
LIB_INSTALLED=$PD2_DATA/libblt_loader.so

if [ ! -d "$PD2_DATA" ]; then
    echo "Could not find PD2 at $PD2_DATA"
    echo "Either you need to install PAYDAY 2, or set the environment variable STEAM_LIBRARY to the location of the steam library it is installed in"
    exit 1
fi

cp "$LIB_FILE" "$LIB_INSTALLED"
```

Where is PAYDAY 2 installed, for you?

**Comment by sysadam** [comment]
Sorry I didn't respond earlier.

PAYDAY 2 for me is installed in

`/media/me/2TB/SteamLibrary/steamapps/common/PAYDAY 2`

**Comment by marco-sciuto** [comment]
Then set STEAM_LIBRARY before running the script
`STEAM_LIBRARY=media/me/2TB/SteamLibrary ./install.sh`

**Comment by RomanHargrave** [comment]
It looks like `STEAM_LIBRARY` was set relatively and not absolutely - put a slash at the beginning like `STEAM_LIBRARY=/media/...`

**Comment by RomanHargrave** [comment]
@sysadam has the issue been resolved?

**Comment by sysadam** [comment]
Yes, sorry for responding late. It fixed it, thank you!
