### ISSUE TITLE
KeyError: 'apps'

### ISSUE THREAD

**Issue by snpster** [blt4linux/blt4l#46]
snp@snp-desktop:~/blt4l$ STEAM_LIBRARY=/media/snp/Ubuntu_Data/SteamLibrary ./install.sh
Checking for libcurl4-openssl-dev
Checking for zlib1g-dev
Checking for cmake
Checking for build-essential
-- Configuring done
-- Generating done
-- Build files have been written to: /home/snp/blt4l/installer_build
[100%] Built target blt_loader
Looking for payday2_release... this could take a moment
Traceback (most recent call last):
  File "/home/snp/blt4l/installer/enable_blt_wrapper.py", line 13, in <module>
    vdf.kv['UserLocalConfigStore']['Software']['Valve']['Steam']['apps']['218620']['LaunchOptions'] = 'env LD_PRELOAD=\\"$LD_PRELOAD ./libblt_loader.so\\" %command%'
KeyError: 'apps'
Traceback (most recent call last):
  File "/home/snp/blt4l/installer/enable_blt_wrapper.py", line 13, in <module>
    vdf.kv['UserLocalConfigStore']['Software']['Valve']['Steam']['apps']['218620']['LaunchOptions'] = 'env LD_PRELOAD=\\"$LD_PRELOAD ./libblt_loader.so\\" %command%'
KeyError: 'apps'
Launch parameters for PAYDAY 2 on all your Steam Profiles have been set to load BLT

I'm a bit out of my depth with this, any help would be appreciated. 

I was originally also getting errors about not finding the dir, so i manually set the steam library. but i have no idea about this one

**Comment by RomanHargrave** [comment]
BLT is installed, but steam isn't configured to use it, so you have to set it yourself. 

The issue here is with the installer, I'll check it out - it should be simple enough to fix.

**Comment by Ozymandias117** [comment]
'apps' is 'Apps' for me. I'm guessing that's going to be an issue based off when you installed Steam.

We could just throw it in a try/except and check apps first then Apps.
