### ISSUE TITLE
How to set $STEAM_LIBRARY to steam library

### ISSUE THREAD

**Issue by Duder963** [blt4linux/blt4l#49]
I start the install.sh with sudo, but then it asks me to set $STEAM_LIBRARY to my library. My Payday2 is installed at /media/duder963/Games/Steam/steamapps/common, so what would I put to set $STEAM_LIBRARY to that?

**Comment by Duder963** [comment]
Okay I sorted that out, but now Cmake is failing. I tried installing OpenSSL following this guide (https://geeksww.com/tutorials/libraries/openssl/installation/installing_openssl_on_ubuntu_linux.php), and now my installer_cmake.log is asking me to set the path to the root in the system variable OPENSSL_ROOT_DIR

**Comment by Duder963** [comment]
Solved THAT, but now it says 
CMake can not determine linker language for target: blt_loader

**Comment by Teraku** [comment]
Same problem. CMake just gives me the following error:

```
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Configuring done
CMake Error at CMakeLists.txt:31 (add_library):
  Cannot find source file:

    subhook/subhook.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: blt_loader
CMake Error: Cannot determine link language for target "blt_loader".
-- Generating done
-- Build files have been written to: /home/hugo/Downloads/blt4linux/installer_build
```

**Comment by Teraku** [comment]
I managed to solve the problem. The subhook directory is not being cloned or downloaded correctly. Downloading it separately fixes the problem.

**Comment by Duder963** [comment]
Now that THAT one's solved, it launches fine, except when I get to configuring Steam, I get this.
Configuring steam: ...
... /home/duder963/.steam/steam/userdata/127161680/config/localconfig.vdf: Failed
Traceback (most recent call last):
  File "/home/duder963/Downloads/blt4l-master/installer//enable_blt_wrapper.py", line 13, in <module>
    vdf.kv['UserLocalConfigStore']['Software']['Valve']['Steam']['apps']['218620']['LaunchOptions'] = 'env LD_PRELOAD=\\"$LD_PRELOAD ./libblt_loader.so\\" %command%'
KeyError: 'apps'
... You may need to restart steam for these changes to take effect.

**Comment by Ozymandias117** [comment]
@Teraku That error you're seeing looks like you didn't run `git submodule update --init`

@Duder963 You stated "I tried installing OpenSSL following this guide"
You should only need to install things from your package manager, and you shouldn't need to mess with OPENSSL_ROOT_DIR. Theoretically the install.sh should ask you to install them, did that not work?

As for the last thing that was stated, about KeyError: 'apps', see #46.
If you make sure libblt_loader.so and the mods folder end up in the Payday folder and add `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%` to your PAYDAY 2 -> Properties -> Set Launch Options it should work.

**Comment by Ozymandias117** [comment]
If you pull your repository up to master, your "KeyError: 'apps'" issue should be solved.
I'm not sure if you're going to have problems still with your statements about OpenSSL, though.

**Comment by Duder963** [comment]
@Ozymandias117 When I ran the install.sh, it didn't ask me to download OpenSSL, so I googled how to download it, and that guide popped up. After realizing it was using an old version and redoing that with the newest version, the OpenSSL worked. I'm new to actually using Linux as my main OS, so the package manager thought didn't even occur to me.

I'll try the launch option you posted as soon as I can.

**Comment by RomanHargrave** [comment]
@Duder963 well, openssl isn't a direct requirement. 

You actually need to openssl version of cURL (but to be honest, I haven't noticed issues with the gnutls version).

**Comment by Duder963** [comment]
Okay, the command worked, however the mods folder wasn't being sent to the Payday 2 folder, so I had to manually move it. Once I did, the BLT worked perfectly. The only real problem is I'm being prompted to download the hook dll, and if I do, the download stops. Other than that, my issue is closed

**Comment by RomanHargrave** [comment]
@Duder963 you can just disable updates for the BLT dll.

For anyone that comes across this issue - you should know that if you just say no to the "missing packages" prompt, you can continue with the build anyways.

**Comment by ca1ek** [comment]
It's really helpful of you @Duder963 to say what exactly you did to `$STEAM_LIBRARY` to make it work. Thanks!
