### ISSUE TITLE
Missing dep Fedora (and installation failures (and some solution)

### ISSUE THREAD

**Issue by LouisLoudogTrottier** [blt4linux/blt4l#50]
On Fedora25, rpmFusion Enabled
the install script is missing curl4-openssl and zlib 
DNF install says the packages are not available.

-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:9 (message):
  One of the needed libraries wasn't found! Exiting

**Comment by LouisLoudogTrottier** [comment]
Downloaded the tar and ran install.sh :

**> install.sh: line 24: lsb_release: command not found**
> [WARNING]  is unkown to installscript!
> Checking for libcurl4-openssl-dev
> Not found.
> Checking for zlib1g-dev
> Not found.
> Checking for cmake
> Not found.
> Checking for build-essential
> Not found.
> Needing these packages: libcurl4-openssl-dev zlib1g-dev cmake build-essential
> Your distribution is unsupported but you can proceed if the packages are installed
> Proceed? [y/N]: y

Since most of those are not in fedora Repo i did (as root of course)

> dnf groupinstall "Development Tools"

also installed pacakge : 

> dnf install curl-devel

And now we have Curl good: 

> Found CURL: /usr/lib64/libcurl.so (found version "7.51.0") 

Installed openssl-devel (as root)
dnf install openssl-devel

DONE with errors:

> -- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
> -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
> -- Configuring done
> CMake Error at CMakeLists.txt:31 (add_library):
>   Cannot find source file:
> 
>     subhook/subhook.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
> 
> CMake Error: CMake can not determine linker language for target: blt_loader
> CMake Error: Cannot determine link language for target "blt_loader".
> -- Generating done
> -- Build files have been written to: /home/llt/Downloads/a/blt4l-1.3-r1/installer_build
> cmake failed (0)
> 
> 

Hope this helps you help me.

**Comment by RomanHargrave** [comment]
Your second error is probably because you didn't check out the subhook submodule.

Could you run `git submodule update --init --recursive` and try building?

**Comment by LouisLoudogTrottier** [comment]
from blt5l-master directory i ran as user:

```
$ git submodule update --init --recursive
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

```

so i ran 
```
$ git init
Initialized empty Git repository
```

ran (succefully) : 
`$ git submodule update --init --recursive`
```

sh install.sh 
/home/llt/Downloads/blt4l-master/installer/framework.sh: line 173: lsb_release: command not found
Updating submodules: OK
Looking for CMakeLists.txt: Found
Note: No package list for 
Looking for PAYDAY 2: Not Found
  The PAYDAY 2 install location could not be determined.
  If you have a steam library located outside of /home/llt/.steam/steam,
  you should set $STEAM_LIBRARY to point to it

```

So i needed to : (change username by your linux username / home folder)
`export STEAM_LIBRARY=/home/username/.steam/steam/steamapps/common/`

then: 
```
sh install.sh 
/home/llt/Downloads/blt4l-master/installer/framework.sh: line 173: lsb_release: command not found
Updating submodules: OK
Looking for CMakeLists.txt: Found
Note: No package list for 
Looking for PAYDAY 2: /home/llt/.steam/steam/steamapps/common/PAYDAY 2/payday2_release
Looking for Steam configs: 1 found
cmake '/home/llt/Downloads/blt4l-master/CMakeLists.txt' -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-march=native -mtune=native' -DCMAKE_C_FLAGS='-march=native -mtune=native'
Looking for installer_build: Found
Running CMake: OK
Building BLT: Failed
Please see the Make log at /home/llt/Downloads/blt4l-master/installer_build/installer_make.log


```

So here's the log:

[installer_make.log.txt](https://github.com/blt4linux/blt4l/files/908642/installer_make.log.txt)


I'm throwing all this at you like this so if someone else have trouble with fedora it can help him. To be honest it's the first time i use github so don't assume i know what i'm doing. I have basic bash knowledge and know my way around Linux so that's less of a worry. If i can make tihs work i promise i'll wrap it all up in a nice how-to-fedora file 4ya. thx again for your time. 

Can't play the game but still having some linux fun with it :D

**Comment by LouisLoudogTrottier** [comment]
if i manually (as user) (do i need to be root to mkae?) i get pretty much the same as in the log file, i assume you just made an echo >> log but here it is 
```

cmake ../
make
anyway
make
[  9%] Building CXX object CMakeFiles/blt_loader.dir/src/hook.cc.o
/home/llt/Downloads/blt4l-master/src/hook.cc:100:5: error: ‘SubHook’ does not name a type
     SubHook     gameUpdateDetour;
     ^~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:101:5: error: ‘SubHook’ does not name a type
     SubHook     luaNewStateDetour;
     ^~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:102:5: error: ‘SubHook’ does not name a type
     SubHook     luaCallDetour;
     ^~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:103:5: error: ‘SubHook’ does not name a type
     SubHook     luaCloseDetour;
     ^~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc: In function ‘void* blt::dt_Application_update(void*)’:
/home/llt/Downloads/blt4l-master/src/hook.cc:14:31: error: ‘SubHook’ has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/llt/Downloads/blt4l-master/src/hook.cc:108:9: note: in expansion of macro ‘hook_remove’
         hook_remove(gameUpdateDetour);
         ^~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc: In function ‘void blt::dt_lua_call(blt::lua_state*, int, int)’:
/home/llt/Downloads/blt4l-master/src/hook.cc:14:31: error: ‘SubHook’ has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/llt/Downloads/blt4l-master/src/hook.cc:123:9: note: in expansion of macro ‘hook_remove’
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc: In function ‘void* blt::dt_dsl_lua_newstate(blt::lua_state**, bool, bool, bool)’:
/home/llt/Downloads/blt4l-master/src/hook.cc:14:31: error: ‘SubHook’ has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/llt/Downloads/blt4l-master/src/hook.cc:141:9: note: in expansion of macro ‘hook_remove’
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc: In function ‘void blt::dt_lua_close(blt::lua_state*)’:
/home/llt/Downloads/blt4l-master/src/hook.cc:14:31: error: ‘SubHook’ has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/llt/Downloads/blt4l-master/src/hook.cc:228:9: note: in expansion of macro ‘hook_remove’
         hook_remove(luaCloseDetour);
         ^~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc: In function ‘void blt::blt_init_hooks(void*)’:
/home/llt/Downloads/blt4l-master/src/hook.cc:285:13: error: ‘gameUpdateDetour’ was not declared in this scope
             gameUpdateDetour.Install    ((void*) do_game_update,    (void*) dt_Application_update);
             ^~~~~~~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:288:13: error: ‘luaNewStateDetour’ was not declared in this scope
             luaNewStateDetour.Install   ((void*) dsl_lua_newstate,  (void*) dt_dsl_lua_newstate);
             ^~~~~~~~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:289:13: error: ‘luaCloseDetour’ was not declared in this scope
             luaCloseDetour.Install      ((void*) lua_close,         (void*) dt_lua_close);
             ^~~~~~~~~~~~~~
/home/llt/Downloads/blt4l-master/src/hook.cc:290:13: error: ‘luaCallDetour’ was not declared in this scope
             luaCallDetour.Install       ((void*) lua_call,          (void*) dt_lua_call);
             ^~~~~~~~~~~~~
CMakeFiles/blt_loader.dir/build.make:206: recipe for target 'CMakeFiles/blt_loader.dir/src/hook.cc.o' failed
make[2]: *** [CMakeFiles/blt_loader.dir/src/hook.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blt_loader.dir/all' failed
make[1]: *** [CMakeFiles/blt_loader.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by LouisLoudogTrottier** [comment]
i think on the right track: don'T scratch your head for nothing i'll post my results here in a few minutes.

**Comment by LouisLoudogTrottier** [comment]
No errors, i can get in game, still have to see if i can match with my windoze buddy


Clone from git and move to the created folder
$ git clone https://github.com/blt4linux/blt4l.git
$ cd blt4

follow instruction on git page
$ git submodule init
$ git submodule update
$ mkdir build
$ cd build
$ cmake ../
$ make

next copy the files to your payday game folder:
libblt_loader.so

And also download the steamruntime and copy the mods/folder inside the game folder.
Make sure not to overwrite the file you maked.

selinux complains (check git page)
$ su
# ausearch -c 'payday2_release' --raw | audit2allow -M my-payday2-hook
# semodule -d my-payday-hook.pp

**Comment by LouisLoudogTrottier** [comment]
No cigar,
I moved the .so file in the root of Payday2
I also move the content ot the symlink mods into the payday folder so i have sometinhg like
PAyday/
-libblt_loader.so
-base/
-downlaods/
-logs/
-saves/
-mods/
--Linux Matchmaking Fix

still Can't team up with windows. 

Anymore way i can debug or see if the API is actualy running?

wow thank alot.

**Comment by RomanHargrave** [comment]
You need to install the mod. BLT just loads it.

You didn't mention in installing the mod (not BLT, but the matchmaking mod).

**Comment by RomanHargrave** [comment]
> I've set the 
> `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%`
> in the lauch option too. I have to remove the %command% part or the game won't launch
>
> the game launch with 
> `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%`

Bot of those strings are the same?

You'll know the BLT is loaded when a menu item appears.

**Comment by LouisLoudogTrottier** [comment]
Yes, the OP issues was about fedora depencecies and that is resolve. Sorry for streaching, i've edited the line for game start up.

Still had issues about build/make, now it worked. Next step is to make sure BLT works. I truely appreciate your support.

**Comment by LouisLoudogTrottier** [comment]
Not sure it will work on other RPM distro but i managed to get it to work on Fedora25, Actualy this worked great on fedora25 with rpmFusion. Just not sure about where i found the zlib but i remember seeing it in yumex so it should be available for DNF

1 You will need these dependencies 
-- As Root --------------------------------
```
dnf groupinstall "Development Tools"
dnf install curl-devel openssl-devel
```

-- As user --------------------------------
2 Clone git and go to the folder
```
git clone https://github.com/blt4linux/blt4l.git
cd blt4l

```
3 Intitialize git and clone the needed subhook
```
git init
git submodule init
git submodule update
git submodule update --init --recursive
```

4 make the build
```
mkdir build
cd build
cmake ..
make
```

5 Install 
```
cd ..
sh ./install.sh
```

!!! If you get an error like "_...you should set $STEAM_LIBRARY to point to it_" 
type this line before running the script **(replace _[username]_ with your linux user name)**:
_(~/.steam/steam is actualy a symlink to your actual installation ei:`~/.local/share/Steam`)_
```
export STEAM_LIBRARY="/home/[username]/.steam/steam/steamapps/common"
sh ./install.sh
```

<hr/>
6 Start or **Restart** steam 

7 Set launch option for PD2:
```
env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%
```

8 Run the game once and it will crash because of selinux.
_You can find it with `tail /var/log/audit/audit.log | grep payday2_release`_

9 Create a policy for the hook
```
ausearch -c 'payday2_release' --raw | audit2allow -M my-blt4l-hook
semodule -i my-payday-hook.pp

```

10 Enjoy.
