### ISSUE TITLE
Merge BLTU update into BLT4Linux

### ISSUE THREAD

**Issue by dribbleondo** [blt4linux/blt4l#51]
Luffy made an update to the regular BLT which fixed the community challenges box colliding with the notifications box: https://modworkshop.net/mydownloads.php?action=view_down&did=19755

It would be a good idea to fix this also in BLT4Linux, don't ya think?

**Comment by RomanHargrave** [comment]
Is this a change to the LUA or the loader API?

**Comment by dribbleondo** [comment]
The LUA, as far as I understand it. It literally fixes one problem, and that's it.

**Comment by RomanHargrave** [comment]
We use the same lua base as The BLT, so those changes would need to go to https://github.com/JamesWilko/Payday-2-BLT-Lua unless we were to fork that and maintain it separately.

**Comment by dribbleondo** [comment]
Gonna Agree with Luffy on Modworkshop and say that Wilko doesn't appear to be Updating the BLT anytime soon. Adding in the BLTU is probably better than forking it and maintaining a seperate build, _Just_ because it fixes one issue, a minor one at that.

I'm about to confirm with Luffy that this works with BLT4Linux also, and they'll likely give you permission to implement the changes

**Comment by RomanHargrave** [comment]
Well, I would _have_ to fork the lua base if I wanted to do that. I'm not averse to doing so, but this opens a whole can of worms because then I am obliged to host updates for the lua base.

**Comment by dribbleondo** [comment]
BLT4Linux itself doesn't have an autoupdater does it? Though, like you said above, it shouldn't need it.

**Comment by RomanHargrave** [comment]
The auto-updater for BLT and the lua has historically and is currently implemented in the lua base, with the lua and the loader being handled as a special mod, similar to other mods that may be installed

**Comment by dribbleondo** [comment]
Okay, good to know. Also, [this unrelated fix](https://github.com/JamesWilko/Payday-2-BLT-Lua/pull/5/files) is a huge oversight on Wilko's part

**Comment by dribbleondo** [comment]
Also, Luffy has given permission to ["Do whatever you want"](http://imgur.com/a/2nT7g) with the BLTU Mod.

**Comment by RomanHargrave** [comment]
Yeah, I can switch to that, but people will still have to manually update their base mod regardless of whether they are on windows or linux.

**Comment by RomanHargrave** [comment]
Done (see release 1.3-r1-1)

**Comment by dribbleondo** [comment]
Seems that Either Wilko really didn't approve of BLTU's existence _or_ the fact that BLT4L was more up to date than _the regular BLT._

Short story, BLT has updated its base to include the bugfixes in BLTU and some more fixes metioned elsewhere. BLT4L will update/ overwrite the BLTU base changes anyway. RIP BLTU.

**Comment by RomanHargrave** [comment]
BLT4L isn't doing it, it's the lua base
