### ISSUE TITLE
Probleme to find PAYDAY 2 install directory

### ISSUE THREAD

**Issue by laz3dots** [blt4linux/blt4l#52]
![prbblt4l](https://cloud.githubusercontent.com/assets/28537620/25811169/6788e3c8-3423-11e7-9b69-68844b4f3611.png)
it says to point steam library but I don't know how, payday 2 is in ~/home/me/.local/share/steam/....

Ubuntu 16.04 LTS 64bits
processor Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 
graphics GeForce 840M/PCIe/SSE2

Any help would be appreciated, thanks

**Comment by pt300** [comment]
2 options to choose from
1. `export STEAM_LIBRARY=~/.local/share/steam; ./install.sh`
2. `link ~/.local/share/steam ~/.steam`

First will just point the configuration script to right place and run it.
Second one will create a link to steam directory in your home directory. That can come handy later.

**Comment by laz3dots** [comment]
Thank you very much, it works wonderfully now !
