### ISSUE TITLE
Cmake problem

### ISSUE THREAD

**Issue by laz3dots** [blt4linux/blt4l#53]
Me again, I recently changed my main hard drive, and so re installed BLT4L but:
![cmketer](https://cloud.githubusercontent.com/assets/28537620/26055331/86d3f976-3981-11e7-95f8-da0f565d142e.png)
![cmakelog](https://cloud.githubusercontent.com/assets/28537620/26055337/8b9302ea-3981-11e7-8553-06556f3f47bc.png)

And again I'm not a Linux pro so I don't know what to do, if someone could help please?
Thanks.

Ubuntu 16.04 LTS 64bits
Processor Intel® Core™ i5-4210U CPU @ 1.70GHz × 4
Graphics GeForce 840M/PCIe/SSE2

**Comment by pt300** [comment]
Log message clearly states you lack OpenSSL development files.
`sudo apt install openssl libssl-dev libcurl4-openssl-dev` should solve the problem.

**Comment by laz3dots** [comment]
Thanks for your help, I have no more error messages, but there's nothing in PAYDAY 2: the game works fine but there's no mod, no mod options, etc.

**Comment by pt300** [comment]
Are you sure you followed build instructions from readme?

**Comment by RomanHargrave** [comment]
@laz3dots Could you post the output of `apt list --installed` for us please? 

You may want to put it on a paste service (like http://paste.qc.to or pastebin)

**Comment by RomanHargrave** [comment]
Closing abandoned. Reopen if you continue to experience problems related to this issue @laz3dots.
