### ISSUE TITLE
$STEAM_LIBRARY error with install

### ISSUE THREAD

**Issue by Yunk21** [blt4linux/blt4l#54]
Running on 64 bit Ubuntu 16.04
When I run the install.sh it cant find my steam library
When I manually followed the path /home/lance/.steam/steam/steamapps/common/PAYDAY
I found the payday 2 files so I have no idea why it's not finding it 

lance@lance-TA970:/Desktop/blt4l-master$ ./install.sh
Updating submodules: OK
Looking for CMakeLists.txt: Found
Checking for libcurl4-openssl-dev: Installed
Checking for zlib1g-dev: Installed
Checking for cmake: Installed
Checking for build-essential: Installed
Looking for PAYDAY 2: find: ‘/home/lance/.steam/steam/steamapps/common/PAYDAY’: No such file or directory
find: ‘2’: No such file or directory
Not Found
  The PAYDAY 2 install location could not be determined.
  If you have a steam library located outside of /home/lance/.steam/steam,
  you should set $STEAM_LIBRARY to point to it
lance@lance-TA970:~/Desktop/blt4l-master$

**Comment by pt300** [comment]
Looks like a problem with unquoted string, lol

**Comment by RomanHargrave** [comment]
that's weird

**Comment by Yunk21** [comment]
Yes it is, I just did a fresh install of payday 2 and the problem still is present. ..

**Comment by RomanHargrave** [comment]
Will you get the latest version and try?

**Comment by Yunk21** [comment]
Here's the cmake log, I got a different error this time.
[installer_cmake.txt](https://github.com/blt4linux/blt4l/files/1021976/installer_cmake.txt)

`Looking for CMakeLists.txt: Found
Checking for libcurl4-openssl-dev: Installed
Checking for zlib1g-dev: Installed
Checking for cmake: Installed
Checking for build-essential: Installed
Looking for PAYDAY 2: /home/lance/.steam/steam/steamapps/common/PAYDAY 2/payday2_release
Looking for Steam configs: 1 found
cmake '/home/lance/Desktop/blt4l-master/CMakeLists.txt' -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-march=native -mtune=native' -DCMAKE_C_FLAGS='-march=native -mtune=native'
Looking for installer_build: Found
Running CMake: Failed
Please see the CMake log at /home/lance/Desktop/blt4l-master/installer_build/installer_cmake.log
`

**Comment by RomanHargrave** [comment]
When you clone the repository, you need to either clone it with `--recursive` or run `git submodule update --init --recursive` in the repo after you clone it.

**Comment by Yunk21** [comment]
This fixed it thanks
