### ISSUE TITLE
Running CMake : Failed 

### ISSUE THREAD

**Issue by RipAimTux** [blt4linux/blt4l#57]
I went to run `./install.sh` and i get the error: 
`Running CMake: Failed
Please see the CMake log at /home/tyler/Downloads/blt4l-master/installer_build/installer_cmake.log ` 

and i go into the file and the error reads 

`-- Configuring done
CMake Error at CMakeLists.txt:31 (add_library):
  Cannot find source file:

    subhook/subhook.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: blt_loader
CMake Error: Cannot determine link language for target "blt_loader".
-- Generating done
-- Build files have been written to: /home/tyler/Downloads/blt4l-master/installer_build ` 

Any Help? Thanks

**Comment by RomanHargrave** [comment]
GH doesn't appear to have been including submodules in code snapshots. You should either download a prebuilt BLT or clone (recursively) the repo.

Nice name BTW.

---- On Sat, 10 Jun 2017 03:35:50 -0700 notifications@github.com wrote ----

I went to run ./install.sh and i get the error:
Running CMake: Failed Please see the CMake log at /home/tyler/Downloads/blt4l-master/installer_build/installer_cmake.log

and i go into the file and the error reads

`-- Configuring done
CMake Error at CMakeLists.txt:31 (add_library):
Cannot find source file:

subhook/subhook.c
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx

CMake Error: CMake can not determine linker language for target: blt_loader
CMake Error: Cannot determine link language for target "blt_loader".
-- Generating done
-- Build files have been written to: /home/tyler/Downloads/blt4l-master/installer_build `

Any Help? Thanks
