### ISSUE TITLE
Payday 2 BLT DLL update

### ISSUE THREAD

**Issue by dje4321** [blt4linux/blt4l#60]
After installing this mod i keep getting asked to update BLT DLL but linux does not use DLLs.
When i click update the game freezes and im i have to force close the game

OS: Fedora 25 on kernel 4.11.3-202
CPU: i7-4710HQ
GPU: Nvidia GTX 860m with bumblee setup for optimus
RAM: 8GB

**Comment by RomanHargrave** [comment]
The game may not be freezing, it may be that paydaymods has been exceptionally slow lately.

This is because the base mod just assumes that you are using Windows. I've made some suggestions to eliminate this behaviour, but base mod development is pretty much stagnant.

**Comment by dje4321** [comment]
Thanks for the response. Glad to know. Getting tired of the constant update notifactions

**Comment by RomanHargrave** [comment]
Yeah, it bothers me too. You should just be able to uncheck the automatic update box next to the DLL's entry in the update manager.
