### ISSUE TITLE
 version 'CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by theo546** [blt4linux/blt4l#61]
Hi, when i try to start PAYDAY 2 with btl4l it doesn't work, the game instant crash with this error:
"/home/theo546/.local/share/Steam/steamapps/common/PAYDAY 2/payday2_release: /usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by /usr/lib/blt4l/libblt_loader_steamrt.so)"

here is youtube video if needed: https://youtu.be/Ps_VEYd8hsA

**Comment by RomanHargrave** [comment]
What distro are you using?

**Comment by theo546** [comment]
Archlinux

**Comment by RomanHargrave** [comment]
Which GCC?

**Comment by RomanHargrave** [comment]
More specifically, which GCC were your system libraries compiled with? Arch started using GCC 7 a week or so ago, but I use GCC 6. 

Try compiling BLT.

**Comment by theo546** [comment]
GCC 7.1.1 20170516

When i try to compile it, it failed, missing files:

`[theo546@theo-archlinux build]$ make
Scanning dependencies of target blt_loader
make[2]: ***  Aucune règle pour fabriquer la cible « ../subhook/subhook.c », nécessaire pour « CMakeFiles/blt_loader.dir/subhook/subhook.c.o ». Arrêt.
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/blt_loader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[theo546@theo-archlinux build]$ 
`

Then, when i download the missings file here: https://github.com/Zeex/subhook

it still fail:

`[theo546@theo-archlinux build]$ make
Scanning dependencies of target blt_loader
make[2]: ***  Aucune règle pour fabriquer la cible « ../subhook/subhook.c », nécessaire pour « CMakeFiles/blt_loader.dir/subhook/subhook.c.o ». Arrêt.
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/blt_loader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[theo546@theo-archlinux build]$ make
[  8%] Building C object CMakeFiles/blt_loader.dir/subhook/subhook.c.o
[ 16%] Building CXX object CMakeFiles/blt_loader.dir/src/hook.cc.o
/home/theo546/Bureau/build/blt4l/src/hook.cc:101:5: error: « SubHook » ne nomme pas un type; vouliez-vous utiliser « subhook_t » ?
     SubHook     gameUpdateDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:102:5: error: « SubHook » ne nomme pas un type; vouliez-vous utiliser « subhook_t » ?
     SubHook     luaNewStateDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:103:5: error: « SubHook » ne nomme pas un type; vouliez-vous utiliser « subhook_t » ?
     SubHook     luaCallDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:104:5: error: « SubHook » ne nomme pas un type; vouliez-vous utiliser « subhook_t » ?
     SubHook     luaCloseDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc: Dans la fonction « void* blt::dt_Application_update(void*) »:
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: « SubHook » n'a pas été déclaré
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:109:9: note: dans l'expansion de la macro « hook_remove »
         hook_remove(gameUpdateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: Dans la fonction « void blt::dt_lua_call(blt::lua_state*, int, int) »:
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: « SubHook » n'a pas été déclaré
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:124:9: note: dans l'expansion de la macro « hook_remove »
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: Dans la fonction « void* blt::dt_dsl_lua_newstate(blt::lua_state**, bool, bool, bool) »:
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: « SubHook » n'a pas été déclaré
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:142:9: note: dans l'expansion de la macro « hook_remove »
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: Dans la fonction « void blt::dt_lua_close(blt::lua_state*) »:
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: « SubHook » n'a pas été déclaré
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:235:9: note: dans l'expansion de la macro « hook_remove »
         hook_remove(luaCloseDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: Dans la fonction « void blt::blt_init_hooks(void*) »:
/home/theo546/Bureau/build/blt4l/src/hook.cc:292:13: error: « gameUpdateDetour » n'a pas été déclaré dans cette portée
             gameUpdateDetour.Install    ((void*) do_game_update,    (void*) dt_Application_update);
             ^~~~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:292:13: note: alternatives suggérées: « getdate_err »
             gameUpdateDetour.Install    ((void*) do_game_update,    (void*) dt_Application_update);
             ^~~~~~~~~~~~~~~~
             getdate_err
/home/theo546/Bureau/build/blt4l/src/hook.cc:295:13: error: « luaNewStateDetour » n'a pas été déclaré dans cette portée
             luaNewStateDetour.Install   ((void*) dsl_lua_newstate,  (void*) dt_dsl_lua_newstate);
             ^~~~~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:296:13: error: « luaCloseDetour » n'a pas été déclaré dans cette portée
             luaCloseDetour.Install      ((void*) lua_close,         (void*) dt_lua_close);
             ^~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:296:13: note: alternatives suggérées: « lua_settop »
             luaCloseDetour.Install      ((void*) lua_close,         (void*) dt_lua_close);
             ^~~~~~~~~~~~~~
             lua_settop
/home/theo546/Bureau/build/blt4l/src/hook.cc:297:13: error: « luaCallDetour » n'a pas été déclaré dans cette portée
             luaCallDetour.Install       ((void*) lua_call,          (void*) dt_lua_call);
             ^~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:297:13: note: alternatives suggérées: « lua_alloc »
             luaCallDetour.Install       ((void*) lua_call,          (void*) dt_lua_call);
             ^~~~~~~~~~~~~
             lua_alloc
make[2]: *** [CMakeFiles/blt_loader.dir/build.make:207: CMakeFiles/blt_loader.dir/src/hook.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/blt_loader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[theo546@theo-archlinux build]$ 
`

so, i don't know what to do...

**Comment by pt300** [comment]
Are you sure you followed instructions from README?
Also, please `LC_ALL=C`. Having to translate compiler warnings and errors is a bit pain in the rear.

**Comment by theo546** [comment]
Hi, here you go,
`[theo546@theo-archlinux build]$ make
[  8%] Building CXX object CMakeFiles/blt_loader.dir/src/hook.cc.o
/home/theo546/Bureau/build/blt4l/src/hook.cc:101:5: error: 'SubHook' does not name a type; did you mean 'subhook_t'?
     SubHook     gameUpdateDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:102:5: error: 'SubHook' does not name a type; did you mean 'subhook_t'?
     SubHook     luaNewStateDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:103:5: error: 'SubHook' does not name a type; did you mean 'subhook_t'?
     SubHook     luaCallDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc:104:5: error: 'SubHook' does not name a type; did you mean 'subhook_t'?
     SubHook     luaCloseDetour;
     ^~~~~~~
     subhook_t
/home/theo546/Bureau/build/blt4l/src/hook.cc: In function 'void* blt::dt_Application_update(void*)':
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: 'SubHook' has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:109:9: note: in expansion of macro 'hook_remove'
         hook_remove(gameUpdateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: In function 'void blt::dt_lua_call(blt::lua_state*, int, int)':
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: 'SubHook' has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:124:9: note: in expansion of macro 'hook_remove'
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: In function 'void* blt::dt_dsl_lua_newstate(blt::lua_state**, bool, bool, bool)':
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: 'SubHook' has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:142:9: note: in expansion of macro 'hook_remove'
         hook_remove(luaNewStateDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: In function 'void blt::dt_lua_close(blt::lua_state*)':
/home/theo546/Bureau/build/blt4l/src/hook.cc:15:31: error: 'SubHook' has not been declared
 #define hook_remove(hookName) SubHook::ScopedRemove _sh_remove_raii(&hookName)
                               ^
/home/theo546/Bureau/build/blt4l/src/hook.cc:235:9: note: in expansion of macro 'hook_remove'
         hook_remove(luaCloseDetour);
         ^~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc: In function 'void blt::blt_init_hooks(void*)':
/home/theo546/Bureau/build/blt4l/src/hook.cc:292:13: error: 'gameUpdateDetour' was not declared in this scope
             gameUpdateDetour.Install    ((void*) do_game_update,    (void*) dt_Application_update);
             ^~~~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:292:13: note: suggested alternative: 'getdate_err'
             gameUpdateDetour.Install    ((void*) do_game_update,    (void*) dt_Application_update);
             ^~~~~~~~~~~~~~~~
             getdate_err
/home/theo546/Bureau/build/blt4l/src/hook.cc:295:13: error: 'luaNewStateDetour' was not declared in this scope
             luaNewStateDetour.Install   ((void*) dsl_lua_newstate,  (void*) dt_dsl_lua_newstate);
             ^~~~~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:296:13: error: 'luaCloseDetour' was not declared in this scope
             luaCloseDetour.Install      ((void*) lua_close,         (void*) dt_lua_close);
             ^~~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:296:13: note: suggested alternative: 'lua_settop'
             luaCloseDetour.Install      ((void*) lua_close,         (void*) dt_lua_close);
             ^~~~~~~~~~~~~~
             lua_settop
/home/theo546/Bureau/build/blt4l/src/hook.cc:297:13: error: 'luaCallDetour' was not declared in this scope
             luaCallDetour.Install       ((void*) lua_call,          (void*) dt_lua_call);
             ^~~~~~~~~~~~~
/home/theo546/Bureau/build/blt4l/src/hook.cc:297:13: note: suggested alternative: 'lua_alloc'
             luaCallDetour.Install       ((void*) lua_call,          (void*) dt_lua_call);
             ^~~~~~~~~~~~~
             lua_alloc
make[2]: *** [CMakeFiles/blt_loader.dir/build.make:207: CMakeFiles/blt_loader.dir/src/hook.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/blt_loader.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
[theo546@theo-archlinux build]$ 
`

**Comment by Ozymandias117** [comment]
I'm incredibly concerned by your statement:

> Then, when i download the missings file here: https://github.com/Zeex/subhook

You should checkout the repository, and run
`git submodule update --init --recursive`


It looks like some major changes have been made to that repo that haven't been accounted for in blt4l. Specifically: https://github.com/Zeex/subhook/commit/bfdb2b4ea6dbd75881096400db43b3f4a276bea7

**Comment by Svenare** [comment]
same issue on arch

**Comment by Svenare** [comment]
same issue 4.11.6-1-ARCH

**Comment by theo546** [comment]
@Ozymandias117 what i said should be ignored, but still can't compile blt4 on archlinux

**Comment by pt300** [comment]
@theo546 a few commits were pushed recently. I suggest you to update repository and try again.

**Comment by theo546** [comment]
thanks, it's finally works fine thanks for work!

**Comment by polarathene** [comment]
For other Arch users, if you're not aware of the issues of the update to OpenSSL 1.1, it causes quite a few packages to break that expect OpenSSL 1.0. But far as I know Arch handled this by keeping OpenSSL at 1.0 until it could be resolved better. Distros based off Arch like Manjaro however did not do this(not sure if everyone citing Arch is using vanilla Arch). `CURL_OPENSSL_3` was a common error though from memory, had it with a few packages from AUR.

**Comment by RomanHargrave** [comment]
Closing abandoned. reopen if you continue to experience related issues.
