### ISSUE TITLE
Blt4l fails to compile

### ISSUE THREAD

**Issue by pt300** [blt4linux/blt4l#63]
It is caused by an include directive in hook.cc introduced in 4c25303398b7458b1600517ec34714df7b65e8e2. File `blt/lapi_version.hh` is referenced, yet it does not exist in repository making the compilation fail.

**Comment by RomanHargrave** [comment]
oh my, that's not good.

A fix will come soon, I've got a _huge_ patch to the game incoming soon, just applying finishing touches.

**Comment by RomanHargrave** [comment]
Should be fixed. Be sure to check out the new tricks
