### ISSUE TITLE
Game crash on start

### ISSUE THREAD

**Issue by Crossik9** [blt4linux/blt4l#65]
I download and install blt4l_2.0-pre1_Ubuntu-trusty.tar.xz
When trying to start, game just crash instantly.

**Comment by RomanHargrave** [comment]
Sorry, I wasn't thinking when I released the latest patch. It's dynamically linked against libc++, which you probably don't have installed (and isn't in steamrt). What distro are you on?

**Comment by Crossik9** [comment]
Ubuntu 17

**Comment by RomanHargrave** [comment]
See if there's a package with a name containing libc++ or libcxx

---- On Mon, 26 Jun 2017 10:12:27 -0700 notifications@github.com wrote ----

Ubuntu 17

**Comment by Crossik9** [comment]
No i cant find any of them

**Comment by dribbleondo** [comment]
In the package manager on Mint, I have libc++1, which i'm taking a fairly good guess that's what you're looking for. Also, make sure libcurl is installed too, as that may be needed for the "hooking"

**Comment by RomanHargrave** [comment]
Yep, watch out for the problem that just came up in #64, though.

---- On Mon, 26 Jun 2017 11:03:48 -0700 notifications@github.com wrote ----

In the package manager on Mint, I have libc++1, which i'm taking a fairly good guess that's what you're looking for.

**Comment by Kazenin** [comment]
Well, this problem does not occur on Fedora, only. This is good and bad at same time.

**Comment by RomanHargrave** [comment]
The problem I'm referring to is directory entry order

**Comment by Crossik9** [comment]
Installing libc++1 doesn't fix the issue

**Comment by Kazenin** [comment]
@Crossik9 Did you install clang too ? About libcxx, remember, install the "devel" version. ex. $ sudo apt-get install libc++-dev

**Comment by RomanHargrave** [comment]
If he's using a prebuilt he doesn't need headers/linker archives

**Comment by RomanHargrave** [comment]
Try an earlier revision (latest 1.x). If you're waiting on mod_overrides, just hang tight.

**Comment by Crossik9** [comment]
Packaging Update 1.3-r1-1 works great, thanks!
