### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by as3mbus** [blt4linux/blt4l#66]
hello, im trying to run installer.sh and build it manually but it seems always come to this error.
this is installer make log.
```
Scanning dependencies of target blt_loader
[  7%] Building C object CMakeFiles/blt_loader.dir/subhook/subhook.c.o
[ 15%] Building CXX object CMakeFiles/blt_loader.dir/src/event.cc.o
[ 23%] Building CXX object CMakeFiles/blt_loader.dir/src/zip.cc.o
[ 30%] Building CXX object CMakeFiles/blt_loader.dir/src/fs.cc.o
[ 38%] Building CXX object CMakeFiles/blt_loader.dir/src/http.cc.o
[ 46%] Building CXX object CMakeFiles/blt_loader.dir/src/log.cc.o
[ 53%] Building CXX object CMakeFiles/blt_loader.dir/src/hook.cc.o
In file included from /home/as3mbus/blt4l/src/hook.cc:18:0:
/home/as3mbus/blt4l/include/lua.hh:43:45: error: ‘ptrdiff_t’ has not been declared
    void         lua_pushinteger(lua_state*, ptrdiff_t);
                                             ^
CMakeFiles/blt_loader.dir/build.make:206: recipe for target 'CMakeFiles/blt_loader.dir/src/hook.cc.o' failed
make[2]: *** [CMakeFiles/blt_loader.dir/src/hook.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blt_loader.dir/all' failed
make[1]: *** [CMakeFiles/blt_loader.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```
im using remastered ubuntu 16.04 and only change the script by steam library directory to be able to detect payday 2 dir.
thank you in advance :)

**Comment by RomanHargrave** [comment]
Do you know which C++ library and version you are using? I think this may just be a missing include on older libraries.

---- On Fri, 30 Jun 2017 17:24:33 -0700 notifications@github.com wrote ----

hello, im trying to run installer.sh and build it manually but it seems always come to this error.
this is installer make log.

Scanning dependencies of target blt_loader
[  7%] Building C object CMakeFiles/blt_loader.dir/subhook/subhook.c.o
[ 15%] Building CXX object CMakeFiles/blt_loader.dir/src/event.cc.o
[ 23%] Building CXX object CMakeFiles/blt_loader.dir/src/zip.cc.o
[ 30%] Building CXX object CMakeFiles/blt_loader.dir/src/fs.cc.o
[ 38%] Building CXX object CMakeFiles/blt_loader.dir/src/http.cc.o
[ 46%] Building CXX object CMakeFiles/blt_loader.dir/src/log.cc.o
[ 53%] Building CXX object CMakeFiles/blt_loader.dir/src/hook.cc.o
In file included from /home/as3mbus/blt4l/src/hook.cc:18:0:
/home/as3mbus/blt4l/include/lua.hh:43:45: error: ‘ptrdiff_t’ has not been declared
    void         lua_pushinteger(lua_state*, ptrdiff_t);
                                             ^
CMakeFiles/blt_loader.dir/build.make:206: recipe for target 'CMakeFiles/blt_loader.dir/src/hook.cc.o' failed
make[2]: *** [CMakeFiles/blt_loader.dir/src/hook.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blt_loader.dir/all' failed
make[1]: *** [CMakeFiles/blt_loader.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

im using remastered ubuntu 16.04 and only change the script by steam library directory to be able to detect payday 2 dir.
thank you in advance :)

**Comment by thankjura** [comment]
Same problem

**Comment by thankjura** [comment]
Added #include <stddef.h> to lua.hh fix this

**Comment by as3mbus** [comment]
ok it works thank you @thankjura
