### ISSUE TITLE
BLT4L installed but not starting with Payday 2?

### ISSUE THREAD

**Issue by unlemci** [blt4linux/blt4l#72]
I installed BLT4L with ./install.sh from this:
https://github.com/blt4linux/blt4l/releases/tag/2.0-pre1

With this result:
https://hastebin.com/eyetuwowul.sql

I think it is installed but idk...
I just launched ./install.sh and tried to start payday 2 it's starting but no mod working...

**Comment by RomanHargrave** [comment]
A couple issues here.

First, it looks like you have steam and payday installed as the root user. 

You really shouldn't do that.

But if you do intend to keep it that way, make sure you are running payday as the same user it was installed for.

**Comment by unlemci** [comment]
Yes i'm sure but what can i do about this?

**Comment by RomanHargrave** [comment]
Well, I'm still not sure what the exact problem is. You gave me a log that shows you running the installer, which _eventually_ successfully installs BLT in and configures the steam installation in /root/.steam.

When you launch PAYDAY 2 does it launch? If it launches, is there no sign of mods being loaded? Where are the mods stored at?

**Comment by RomanHargrave** [comment]
Since you are using the pre2-1 build, 

1. What distro are you using (and what release, if your distro is releas-based)?

2. Do you have libcxx installed?

3. What is the output of `ldd /path/to/libblt_loader.so` 

4. Did payday work correctly without BLT?

**Comment by unlemci** [comment]
Yes it's launch well... But i installed `WolfHud` and it didn't effect any hud or interface... Then i understand BLT4L is not working.

Mods are stored in here: `/root/.steam/steam/steamapps/common/PAYDAY 2/mods/`
I'm using `Elementary OS 0.4.1 Loki` > it uses Ubuntu 16.04.2 LTS
Libcxx idk am i installed... I look to `dpkg -l` and i can't found libcxx.
also for the `ldd` output: https://hastebin.com/meqiqidasi.rb
And Payday 2 is worked great without BLT...

Also i have got `Bumblebee` for my Nvidia Card i searched on internet, somewhere i saw i have to add a small code to launch's option on steam.
Code is this: `env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%`
From here: https://www.youtube.com/watch?v=E2M8FQqQBKA

But i can't add that code because i can't start payday 2 with that code. I'm launching my payday 2 with this code `primusrun %command%`.
It does just run that program in GPU. (if you don't know what is primusrun)

I'm sorry i'm just a linux user and want to play with mods on my linux machine :)

**Comment by RomanHargrave** [comment]
`env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" primusrun %command%`

**Comment by unlemci** [comment]
I added this and Payday 2 is not launching... :/

**Comment by RomanHargrave** [comment]
Is it possible for you to launch it without optimus (primusrun) and only with BLT? 

---- On Sat, 12 Aug 2017 11:17:34 -0700 notifications@github.com wrote ----

I added this and Payday 2 is not launching... :/

**Comment by unlemci** [comment]
I can't launch without optimus...

**Comment by RomanHargrave** [comment]
try `primusrun env LD_PRELOAD="$LD_PRELOAD ./libblt_loader.so" %command%`

**Comment by unlemci** [comment]
Again didn't launch Payday 2...

**Comment by RomanHargrave** [comment]
And you put primusrun _before_ env? I just want to make sure that BLT isn't causing primusrun to fail.

If I had to guess, you are missing libcxx. If you don't care about `mod_overrides` support, try an older version. I'm not sure if libcxx is available from canonical for Ubuntu 16.04.2, and if it is, I am unsure of the package name.

**Comment by unlemci** [comment]
Can't i debug with something else?

**Comment by RomanHargrave** [comment]
Its a little bit involved, but yes. First, can you please try using an older BLT or compiling one?
