### ISSUE TITLE
Oddity?: Disabling BLT4L, yet Mod_overrides still works.

### ISSUE THREAD

**Issue by dribbleondo** [blt4linux/blt4l#73]
Correct me if i'm wrong, but does the BLT4L lua hook enable Mod_overrides?, or does BLT4L somehow actually patch and modifies the binary itself to activate mod_overrides.

I ask this because when testing something, Mod_overrides functionality stayed, even when I removed the BLT4L command.

**Comment by RomanHargrave** [comment]
BLT4L applies a patch to PAYDAY at runtime

**Comment by RomanHargrave** [comment]
But it is not permanent

**Comment by dribbleondo** [comment]
So, as soon as remove the command from the steam launch options, Mod_overrides should be disabled, yes?

Because from what I can make out, that's not happening. Either Overkill has actually implemented Mod_overrides into the Linux Port, the game somehow _"Knows"_ what to look for without the command, or I'm a special birdie.

**Comment by RomanHargrave** [comment]
That's interesting. Maybe it builds a database of overrides that it saves?

While it's within the realm of possibility for overkill to have fixed `mod_overrides`, it's not very probable. Reliable contact with the developers would certainly help, but they are hard to get in touch with.

**Comment by dribbleondo** [comment]
I'm gonna rename the mod_overrides folder, which should destroy any link to it, even if it uses a database of sorts. I'll keep ya posted.

**Comment by dribbleondo** [comment]
Some progress: downloaded a menu re-texture I knew I hadn't used from modworkshop....and it worked. 

Overkill appears to have actually given us Linux folk Mod_overrides...and not announce that they'd done so.

I'd need other people to see if this is the case though. One persons install is not proof.

**Comment by RomanHargrave** [comment]
Have someone with a pristine install check.

**Comment by Ozymandias117** [comment]
Certainly seems like it's in official now.

I hadn't launched Payday 2 since June 2nd, and was on blt4l commit 6a3417f5ab36296e4f405cc5135d370ff54ccd7f (enquote STEAM_LIBRARY in installer framework).

Removing the LD_PRELOAD and launching, I'm seeing mods from mod_overrides, even though I never had a blt4l that supported it.

**Comment by dribbleondo** [comment]
So it seems like Mod_overrides was added into the Linux version without Overkill telling us between June - August.

Thanks to the way steam works, **[we can download archived versions of Payday 2 manually](https://steamcommunity.com/sharedfiles/filedetails/?id=892936753)**

if we know the exact update, then we'll know when they added mod_overrides support.

**Comment by RomanHargrave** [comment]
I kind of want to have a look through PAYDAY after that mod_overrides update. I had told Joakim how to fix the issue, so that could have been it, but I wonder if it brings some _helpful_ changes to the asset database.

**Comment by RomanHargrave** [comment]
Closing since nothing needs to be done. Feel free to keep discussing in here though.
