### ISSUE TITLE
BLT4L trying to update the Windows hook and failing

### ISSUE THREAD

**Issue by MindfulProtons** [blt4linux/blt4l#74]
On Fedora 26 (XFCE), BLT notifies me about the update to the DLL, and I try to update it, and it hangs at "extracting archive..."

**Comment by dribbleondo** [comment]
Ignore it. You don't need to update the DLL.

To prevent it, go to your mods folder, and find the "saves" folder. look for a text file called "blt_revision.txt", then edit the number inside to be "5".
