### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by PickleRo1** [blt4linux/blt4l#77]
I had a BLT4Linux version installed already in my Payday 2 folder but the mod_overrides didnt work. 
That version only had the mods folder with the other folders inside, the readme file, the libblt_loader.so and the blt license and another one which is install.sh

Installing the latest version i saw that there was a new folder (.installer). puttin all of those inside and putting the commands in launch options doesnt open the game.
Can someone help me step by step installation?

**Comment by RomanHargrave** [comment]
The .installer folder just contains the installer libraries. Its not needed to run BLT.

As long as Steam is configured properly, and the .so file is in the same folder as the executable. You can run the `install.sh` script to do that automatically, if you need.

---- On Mon, 28 Aug 2017 07:09:21 -0700 notifications@github.com wrote ----

I had a BLT4Linux version installed already in my Payday 2 folder but the mod_overrides didnt work.
That version only had the mods folder with the other folders inside, the readme file, the libblt_loader.so and the blt license and another one which is install.sh

Installing the latest version i saw that there was a new folder (.installer). puttin all of those inside and putting the commands in launch options doesnt open the game.
Can someone help me step by step installation?
