### ISSUE TITLE
BLT LuaJit 

### ISSUE THREAD

**Issue by Kazenin** [blt4linux/blt4l#78]
Hello @RomanHargrave and @ZNixian. Would you have a forecast to launch this new feature?

**Comment by dribbleondo** [comment]
BLT4Linux doesn't need to dpo anything because of the way it's designed, as far as I understand it.

though it would be a good idea to port over the new download/ update manager anyways

**Comment by ZNixian** [comment]
I'm pretty sure we'd need to be some changes, if the base game changes to LuaJIT. I don't think that'd be too difficult, so long as they still include the symbols we're currently using.

@dribbleondo What's this about a new download manager?

**Comment by RomanHargrave** [comment]
Duplicate of #55

**Comment by dribbleondo** [comment]
@ZNixian [https://github.com/JamesWilko/Payday-2-BLT/wiki/Whats-New-in-BLT-2](url) there's a new UI for the download manager, mod info and Mod manager. sorry about reopening this thread =/
