### ISSUE TITLE
Formalise a naming and formatting convention

### ISSUE THREAD

**Issue by RomanHargrave** [blt4linux/blt4l#8]
I was working on some code and noticed a few things that I would like to sort out:

Firstly, I would like to avoid preprocessor macros at all costs. If they must be used, they should be clear in what they do. e.g. if they define or assign based on an input name, they should not append or prepend to the definee or assignee name (e.g. `olua_...`).

Secondly, I would like to suggest that we adopt the following naming and namespacing conventions

```
PREPROCESSOR_DEF
name_space
function_name // capital letters are OK after the first letter. first letter should always be lower case
ConstVarName
localVarName
paramName
ClassName
```

Thirdly, the following formatting conventions:

```c++
// Brace on next line except for the following cases

namespace my_namespace { // end this line here
    // indent brace contents ALWAYS, do not leave in line with parent
} // clear line...

class MyClass { // end line here
};

inlineArray = { /* contents */, // comma ends line when overflowing
};

#define MACRO_USING_COMPOUND_EXPR ({ \
    exprBody(); });

// class def/dec:

class MyClassName { // clear line
    public:
        // indent access classifier groups
    protected:
    private:
}; // clear line...

// the same rules apply to structs, enums, etc...

// when you extend an expression, move binary operators to the beginning of the next line if they
// overflow the current line

if ( (COMPLEX_IF_EXPR && ....) || THAT && (THIS + THAT)
     || OTHER_THING )
{  // nothing here please. always align with parent token, not GNU style
    // indent
}

// function declaration
__attribute__((attribute (param)))
static volatile const ReturnType const
function_name (ParamType paramOne)
{
    return returnTypeInstance;
}

// Type modifier placement

void* pointerToTheLeft;
void& refToTheLeft;

```

Please also use scope blocks _liberally_. They are an excellent way to provide a visual understanding of where something is happening at no run-time cost, and without comment abuse.

This issue will be closed once all current code is compliant.

**Comment by LeonardKoenig** [comment]
Nice idea, but I'll definitely have to retrain my fingers for that xD

I've been mostly sticking to the Linux coding style before and because my vim's set up that way I already included the modelines to at least fix that ;-)

The `setcall()` macro looks a bit weird but I think it's ok as long as we add a comment (*cough* I should've possibly done that before already ^^) -- I do not have an idea on how to properly remove it.

I'd add to the codesample on how indent is done.

**Comment by RomanHargrave** [comment]
@LeonardKoenig for setcall, I'd like to revert back to the (field, "call name") variant. That way we can use different symbol names when we need to.

**Comment by LeonardKoenig** [comment]
We can definitely do so, if you prefer. I don't have anything against nor pro-macros.

**Comment by LeonardKoenig** [comment]
Ok, pushed changes
