### ISSUE TITLE
The payday install location could not be determined

### ISSUE THREAD

**Issue by PickleRo1** [blt4linux/blt4l#80]
![image](https://user-images.githubusercontent.com/31410889/30205868-e024c7be-9492-11e7-87ed-5968e1d8f7e0.png)

I have Payday 2 installed in /home/cosmyn/.local/share/Steam/steamapps/common/PAYDAY 2
Creating a new download library in Steam and setting it to /home/.steam/steam doesn't work
![image](https://user-images.githubusercontent.com/31410889/30205979-5277316c-9493-11e7-9f0a-6f6aa43b8200.png)
If someone could teach me how to move the steam library to the correct location i will be very happy

**Comment by RomanHargrave** [comment]
You don't need to move your steam library. You can tell the script where it is.

More importantly, though, you are missing packages, and your repo doesn't have them. You downloaded a repo snapshot and don't have the build dependencies. 

I'm going to make new prebuilts today, hopefully, if I find time. So hang on and use those, unless you want to build from source - in that case, use git.

I think I'll work on the installer some today also.

**Comment by PickleRo1** [comment]
Ok, so i'm downloading the missing packages with synaptic packet manager, could u tell me how i can tell the script where payday is located?

**Comment by marco-sciuto** [comment]
just set it before the script
```
STEAM_LIBRARY=~/.local/share/Steam/ ./install.sh
```

**Comment by PickleRo1** [comment]
@marco-sciuto Thanks that worked but now i have another error :(
It fails to load CMake : 
![image](https://user-images.githubusercontent.com/31410889/30241416-9d0b51ec-958b-11e7-81ba-ca653d3b8253.png)

**Comment by marco-sciuto** [comment]
For `realpath`
```
sudo apt-get install coreutils
```

To fix the other big red message, just clone the git repo:
```
git clone https://github.com/blt4linux/blt4l.git
cd blt4l
```

**Comment by PickleRo1** [comment]
Seems it worked but some mods make blt not run properly. Like i installed WolfHUD and the game had a blackscreen after 1 second of loading. Also some mods make the "lua mods" option freeze the game
mod_overrides mods work fine

**Comment by dribbleondo** [comment]
This is a problem with the fact that @RomanHargrave hasn't updated the base folder for blt 2 yet. I made a build **[HERE](https://drive.google.com/file/d/0B4VxtGqhacqZdmJYUGNxNGZ5VlU/view)** that'll work, but uses the p1 loader, not the newer releases loader.

**Comment by PickleRo1** [comment]
Do i need to paste the files from that google drive into the repository i'm running install.sh?

**Comment by dribbleondo** [comment]
Put in in the Payday 2 folder.

**Comment by PickleRo1** [comment]
I did that and now the game won't open at all, steam says it's running, there is a "
payday2_release" process in the system monitor and also a "sh" process

**Comment by PickleRo1** [comment]
I might go and try the latest release and see if that works for me

**Comment by RomanHargrave** [comment]
@PickleRo1 is the issue still present?

**Comment by PickleRo1** [comment]
i don't know i switched to windows but from what i remember the new version
of blt from that day made the game froze when opening mod manager

**Comment by RomanHargrave** [comment]
ok

**Comment by tskxz** [comment]
> just set it before the script
> 
> ```
> STEAM_LIBRARY=~/.local/share/Steam/ ./install.sh
> ```

After that, it appearing "Please see the Make log at /home/tanjil/blt4l/installer_build/installer_make.log"
