### ISSUE TITLE
Dual-basefolder

### ISSUE THREAD

**Issue by ZNixian** [blt4linux/blt4l#82]
Since we have vm.dofile, it may be possible to patch in the old base folder at runtime for old versions of mods, or those that haven't updated.

Since this is half-related to BLT4L (vm.dofile), any ideas on where this should go?

**Comment by ZNixian** [comment]
It's currently at [ZNixian/Payday-2-BLT-Lua#compat](https://github.com/ZNixian/Payday-2-BLT-Lua/tree/compat), if anyone is interested.

**Comment by RomanHargrave** [comment]
You should bring this up at [JamesWilko/Payday-2-BLT-Lua](/JamesWilko/Payday-2-BLT-Lua)

**Comment by RomanHargrave** [comment]
Closing not-a-bug, unrelated
