### ISSUE TITLE
new functions needed for BLT2 lua

### ISSUE THREAD

**Issue by BangL** [blt4linux/blt4l#85]
blt4l currently misses 3 file.* functions, which got introduced for the new auto-updater method. these are:  

file.DirectoryHash(path)  
https://github.com/JamesWilko/Payday-2-BLT/commit/cca3dbdbaa6d1da557e8a43f2b2499d0c21f1e69
https://github.com/JamesWilko/Payday-2-BLT/commit/2881b9b957883a438ecd16ca1a35e2920b18939f

file.FileHash(path)
https://github.com/JamesWilko/Payday-2-BLT/commit/a46f20e6210c595005dd672313ed7d92b3d474b4

file.MoveDirectory(source, target)
https://github.com/JamesWilko/Payday-2-BLT/commit/c1f6b46d5320f84da1437aa8e5397a7ed32b18cb

**Comment by RomanHargrave** [comment]
Yes, I have been meaning to add these.

**Comment by ZNixian** [comment]
Can you hash the attached sample files, and also the whole directory - I'd like to make sure the hashes match that of the windows version.

[random_files.zip](https://github.com/blt4linux/blt4l/files/1307807/random_files.zip)

**Comment by ZNixian** [comment]
I've checked using sha256sum and reading the windows BLT source code, and I think my implementation is accurate. Opening PR.

**Comment by RomanHargrave** [comment]
Closed RE #87 

@ZNixian BTW inserting "Closes #XX" in to a commit will close the mentioned issue(s) FYI
