### ISSUE TITLE
Newer versions of beardlib does not work

### ISSUE THREAD

**Issue by Kazenin** [blt4linux/blt4l#88]
Hello my friends.

I tested some mods using beardlib and older versions works well, but the newer, not. See:

```
09:59:57 PM Error: LUAErrRun loading LUA file mods/BeardLib/BeardLibCore.lua
09:59:57 PM Error: mods/BeardLib/Classes/FileIO.lua:4: attempt to call method 'open' (a nil value)
09:59:57 PM Error: LUAErrRun loading LUA file mods/BeardLib/BeardLibInit.lua
09:59:57 PM Error: [string "core/lib/system/coremodule.lua"]:124: core:_lookup(...) is for debugging only!
09:59:57 PM Lua: [ERROR] Unable to find ModCore from BeardLib! Is BeardLib installed correctly?
09:59:57 PM Lua: [ERROR] Unable to find ModCore from BeardLib! Is BeardLib installed correctly?
09:59:57 PM Error: LUAErrRun loading LUA file mods/BeardLib/BeardLibCore.lua
09:59:57 PM Error: mods/BeardLib/BeardLibCore.lua:172: attempt to index field 'config' (a nil value)
09:59:57 PM Error: LUAErrRun loading LUA file mods/BeardLib/BeardLibCore.lua
``` 

The BLT2.x mods are using this newer version of beardlib. Is possible fix this issue?
The mods tested are [assault states](https://modworkshop.net/mydownloads.php?action=view_down&did=19391) and [wave survived](https://modworkshop.net/mydownloads.php?action=view_down&did=17949)

**Comment by RomanHargrave** [comment]
`09:59:57 PM Error: mods/BeardLib/Classes/FileIO.lua:4: attempt to call method 'open' (a nil value)`

I'm guessing that's because it wants to do some Diesel File IO. @simon-wh.

Diesel does not export these functions for Linux. We could implement some of them, but we could run in to issues with the file handles, since they need to match the corresponding diesel object, or can be passed to methods that need to talk directly to diesel.

**Comment by ZNixian** [comment]
```
function FileIO:Open(path, flags)
	if SystemFS then
		return SystemFS:open(path, flags)
	else
		return io.open(path, flags)
	end
end
```

Now we have `SystemFS`, it's trying to use that rather than `io`.

If `io` works on both platforms, using that over SystemFS would probably be the best option.

**Comment by BangL** [comment]
i already provided a solution here: https://github.com/blt4linux/blt4l/issues/79#issuecomment-329737599

**Comment by Kazenin** [comment]
Linux IO Compat from @BangL is the current solution http://download.paydaymods.com/download/latest/556
The mods I tested are working correctly. Thanks @BangL

**Comment by RomanHargrave** [comment]
Closing unresolved satisfactory
