### ISSUE TITLE
mod_overrides implemented by base game; BLT version redundant

### ISSUE THREAD

**Issue by ZNixian** [blt4linux/blt4l#89]
From my testing, launching PD2 without BLT4L installed now shows up what's in mod_overrides. I haven't tested to see if the overrides actually work either way, however.

**Comment by dribbleondo** [comment]
**[I noted this oddity back in early august](https://github.com/blt4linux/blt4l/issues/73)**, and Overkill, in their infinite wisdom, _didn't tell us about it_ .Probably because RAID was more important.

**Comment by ZNixian** [comment]
Whoops, missed that. Thanks.

**Comment by RomanHargrave** [comment]
BLT is built without it by default now.

**Comment by ZNixian** [comment]
As in, with USE_LIBCXX disabled or has the code been removed?

**Comment by RomanHargrave** [comment]
The code is still there, but the build scripts do not generate packages with it enabled.
