### ISSUE TITLE
Please don't delete old release files 

### ISSUE THREAD

**Issue by zekesonxx** [blt4linux/blt4l#91]
![ss-16-09-2017-135526](https://user-images.githubusercontent.com/965509/30514614-c35a9a28-9ae6-11e7-9dd4-536239c2235d.png)

**Comment by RomanHargrave** [comment]
I did that because those release files were bad. That revision has the wrong lua submodule.

**Comment by RomanHargrave** [comment]
I need to take down the whole release since the notes are wrong
