### ISSUE TITLE
lua errors dont lead into a crash-to-desktop

### ISSUE THREAD

**Issue by BangL** [blt4linux/blt4l#93]
lua errors should lead into a crash, since anything else could even lead into savegame corruption.
plain pd2 and blt4w behaves like that, only blt4l does not.
i still think that an optional just-log debug mode is useful and legit for devs though.

**Comment by ZNixian** [comment]
Do you have a sample mod that you know crashes on the windows version?

**Comment by BangL** [comment]
just put any faulty code.. its already enough to just call a not existing
function.
im already in my bed for today.

**Comment by ZNixian** [comment]
Okay, I've got basic support for generating a `crash.txt` file and `exit()`ing the game when an error occurs.

This can be disabled by setting BLT_CRASH to CONTINUE, in which case it will act as it does currently, only it also prints the Lua stacktrace to the log.
