### ISSUE TITLE
Lua: SystemFS:list missing

### ISSUE THREAD

**Issue by Kazenin** [blt4linux/blt4l#96]
Hello friends,

I tested this new mod and this log appeared:

```
09:23:42 PM Lua: [BLT] Setting up mod: Void UI
09:23:42 PM Error: LUAErrRun loading LUA file mods/Void UI/main.lua
09:23:42 PM Error: attempt to call a string value
```
How Can I fix this?

**Comment by RomanHargrave** [comment]
check that it's not a case sensitivity problem

**Comment by Kazenin** [comment]
Hello @RomanHargrave,

I change from `mods/Void UI/Main.lua`to `mods/Void UI/main.lua` and this log appeared:

```
09:43:14 PM Error: lua_call: error in lua_pcall: mods/Void UI/main.lua:304: attempt to call method 'list' (a nil value)
09:43:14 PM Error: lua_call: error in lua_pcall: [string "lib/setups/setup.lua"]:753: attempt to index field 'weapon_factory' (a nil value)
09:43:14 PM Error: lua_call: error in lua_pcall: [string "lib/setups/setup.lua"]:803: attempt to index global 'game_state_machine' (a nil value)
```

**Comment by RomanHargrave** [comment]
at that point, it looks like the mod expects things that have either been removed or are not present in BLT, or you are missing dependencies

**Comment by Kazenin** [comment]
I don`t have idea...

**Comment by RomanHargrave** [comment]
since BLT is (primarily) only responsible for facilitating the execution of new scripts in the preexisting lua environment, script errors that aren't related to BLT API calls are not within the scope of BLT

**Comment by RomanHargrave** [comment]
Though game_state_machine is, IIRC, a common global. Are other plugins working?

**Comment by ZNixian** [comment]
@Kazenin You could try building my work-in-progress error.txt-supporting version ([ZNixian/blt4l](https://github.com/ZNixian/blt4l), and check the error.txt file in mods/logs for a stack trace.

**Comment by Kazenin** [comment]
@RomanHargrave yes, other plugins I use are working.
@ZNixian how to proceed?

**Comment by ZNixian** [comment]
@Kazenin As in, how to build it? If you've got it installed, pastebin the error.txt file in your mods/logs folder.

**Comment by Kazenin** [comment]
Hello @ZNixian. This file does not exist. I have log.txt and <date>_log.txt files

**Comment by ZNixian** [comment]
@Kazenin They should only be generated after a Lua error, which on my WIP fork should generate a crash.

**Comment by Kazenin** [comment]
but the game does not crash, I have a black screen, instead

**Comment by ZNixian** [comment]
@Kazenin Are you using my fork? If not, I can either send you the correct `libblt_loader.so` or you can compile it yourself:

```
git clone https://github.com/ZNixian/blt4l.git errorlog-blt4l
cd errorlog-blt4l
git submodule init
git submodule update
mkdir build 
cd build
cmake .. 
make
```

**Comment by Kazenin** [comment]
@ZNixian thank you. See the output:
```
Lua runtime error: mods/Void UI/main.lua:304: attempt to call method 'list' (a nil value)

stack traceback:
	mods/Void UI/main.lua:304: in function 'func'
	mods/base/req/core/Hooks.lua:109: in function 'Call'
	mods/base/lua/MenuManager.lua:11: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "lib/setups/setup.lua"]:334: in function 'init_managers'
	[string "lib/setups/menusetup.lua"]:229: in function 'init_managers'
	[string "core/lib/setups/coresetup.lua"]:379: in function <[string "core/lib/setups/coresetup.lua"]:278>
```

**Comment by ZNixian** [comment]
Okay, found it. It's trying to use `SystemFS:list`.

@RomanHargrave Is there a substitute in the IO library?

Reopening as this is a problem with BLT.

**Comment by RomanHargrave** [comment]
no, we currently do not have a `SystemFS:list` implementation. 

The fact that it is yet to be implemented still may be due to the return type being effectively opaque to us (e.g. we cannot create it or interact with it), though there is a chance that may not be the case. I know I had it on the list of SystemFS functions needed in BLT4L.

**Comment by BangL** [comment]
this might help:
http://download.paydaymods.com/download/latest/556

**Comment by Kazenin** [comment]
@BangL thanks for your help. I tried this one but I had these results:

Log: 
```
05:30:12 PM Error: mods/Void UI/main.lua:87: attempt to call method 'create_entry' (a nil value)
05:30:12 PM Lua: [Error] mods/Void UI/main.lua:87: attempt to call method 'create_entry' (a nil value)
```
Image from my game: https://pasteboard.co/GNAl9ED.png
Original Image: https://goo.gl/Qvw3gH

**Comment by BangL** [comment]
which means it fixed the problem. this is a new one.

I guess its using DB:create_entry there? its used to load images at
runtime. this isn't possible on linux yet, and therefore can't really be
fixed for now, only surpressed.

**Comment by BangL** [comment]
its basically the problem as this one: #70

**Comment by ZNixian** [comment]
@BangL Since this issue was originally about `SystemFS:list`, we might as well use it for that. I'll rename the issue.

**Comment by Fanged-Hex** [comment]
Hello, I'm one of the developer of Void UI (the mod that use SystemFS:list function).
We are aware of this bug : this part of our code is to load our custom texture we use for our hud.

So I will follow this discussion to know when this bug can be fixed :)

**Comment by dribbleondo** [comment]
Did some messing about and VoidUI works =D. Tried loading the custom heist: **[Enemy Spawner](https://modworkshop.net/mydownloads.php?action=view_down&did=20663#description)** but it crashes as you get to the briefing screen (the "ready up screen" before the heist). 

`Lua runtime error: [string "core/lib/utils/dev/editor/coreworlddefinition..."]:249: attempt to index field 'world_data' (a nil value)

stack traceback:
	[string "core/lib/utils/dev/editor/coreworlddefinition..."]:249: in function 'parse_continents'
	[string "core/lib/utils/dev/editor/coreworlddefinition..."]:44: in function 'WorldDefinition_init'
	mods/BeardLib/Hooks/CoreWorldDefinition.lua:10: in function 'WorldDefinition_init'
	mods/BeardLib/Hooks/CoreWorldDefinition.lua:10: in function 'init'
	[string "lib/utils/dev/editor/worlddefinition.lua"]:6: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "core/lib/utils/dev/editor/worldholder.lua"]:49: in function 'init'
	[string "core/lib/utils/coreclass.lua"]:35: in function 'new'
	[string "lib/setups/gamesetup.lua"]:633: in function 'init_game'
	[string "core/lib/setups/coresetup.lua"]:402: in function <[string "core/lib/setups/coresetup.lua"]:278>`

**Comment by Kazenin** [comment]
@dribbleondo all custom heists are crashing with BLT4L

**Comment by ZNixian** [comment]
BeardLib is somewhat of a mess; this does not particularly surprise me.

**Comment by RomanHargrave** [comment]
@Fanged-Hex @Kazenin @BangL closing unresolved WRT satisfactory fixes from BangL's `ioc` mod. Reopen if needed.

WRT BangL's IO compatibility mod, we should investigate shipping it with BLT4L for the time being. That's not to say it would be ideal to ultimately share the SystemFS implementation with windows for perfect compatibility.
