### ISSUE TITLE
See if creating a SuperBLT4L hook is possible [Enhancement?]

### ISSUE THREAD

**Issue by dribbleondo** [blt4linux/blt4l#99]
More info [here](https://superblt.znix.xyz/) 

Might be beneficial as it allows for xml changes without the need for .pdmod patching, as well as OGG support for music (though I feel that may never happen on **Linux...)**

**Comment by ZNixian** [comment]
This is something I've been getting around to doing. I made sure to base the XAudio stuff (name is only coincidental with the DirectX audio system) off OpenAL specifically for this purpose.

I initially did all my research/early prototyping on GNU+Linux, and then ported it over to Windows, thanks to the binaries not being stripped on GNU+Linux.

I'll do some work on separating the SuperBLT stuff from the rest of BLT4W, as I have used very little (if any) windows-specific stuff in there.

**Comment by dribbleondo** [comment]
Awesome. Glad _someone_ is looking into it =)

**Comment by RomanHargrave** [comment]
I'll hopefully be able to sit down and catch up next week. So i can definitely look at this and see what needs to be added for proper support.

**Comment by ZNixian** [comment]
I've done quite a bit of work building headers on many of the relevant classes, so I'll throw them on the wiki at some point.

**Comment by RomanHargrave** [comment]
Adding the headers to the include directory in blt4l would probably be a good idea.

**Comment by Kazenin** [comment]
How to compile on Linux??

**Comment by ZNixian** [comment]
Progress update: I've separated out (with the exception of the debugging module, which uses Winsock and I haven't been bothered to look at yet) all the windows-specific code in SuperBLT is moved into it's own module; I'll try merging it and the relevant parts of BLT4L together, and hopefully get a single codebase for both the Windows and GNU+Linux versions of SuperBLT.

**Comment by dribbleondo** [comment]
awesome work =D

**Comment by dribbleondo** [comment]
OK, did some compiling and (finally) figured out how to load the damn thing. Upside is that Custom Music Tracks work! [Downside is the file to give it it's name doesn't.
](https://imgur.com/a/xGF5Sq9)
I did a compile on Mint 18.3 as usual, and [uploaded it here](https://drive.google.com/open?id=1qcZ3-FFTbmI075pzNyY2h_XtRdnnTTDl) for those interested in trying it out on Debian-based systems, like Ubuntu, Mint and the like.

**Comment by Kazenin** [comment]
I will try in fedora

**Comment by Kazenin** [comment]
@dribbleondo how to compile ?

**Comment by dribbleondo** [comment]
You require Clang 3.5 or above, apart from that, use the compile instructions on the readme

**Comment by Kazenin** [comment]
in Fedora:

```
$ sudo dnf install openal-soft-devel libcxx-devel openssl-devel clang-devel zlib-devel cmake
$ git clone --recursive https://gitlab.com/znixian/payday2-superblt.git
$ cd payday-superblt && mkdir build && cd build
$ cmake -DUSE_LIBCXX=1 ..
$ make
```
Several warnigs created but the process done
[100%] Linking CXX shared library libsuperblt_loader.so
[100%] Built target superblt_loader

```
$ ldd libsuperblt_loader.so 
	linux-vdso.so.1 (0x00007ffcecd7f000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f82166fa000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f8216479000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f821620d000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f8215d81000)
	libopenal.so.1 => /lib64/libopenal.so.1 (0x00007f8215ae7000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f821575e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8215448000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8215231000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8214e5c000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f8214c37000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f8214a1a000)
	libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f82147ed000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f82145df000)
	libssl3.so => /lib64/libssl3.so (0x00007f821438d000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f8214166000)
	libnss3.so => /lib64/libnss3.so (0x00007f8213e3c000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f8213c0c000)
	libplds4.so => /lib64/libplds4.so (0x00007f8213a08000)
	libplc4.so => /lib64/libplc4.so (0x00007f8213803000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f82135c4000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f82133a5000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f82131a1000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f8212f54000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f8212c6d000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f8212a3a000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f8212836000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f8212627000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f82123d5000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f82121cd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8216bfb000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f8211e4d000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f8211c3e000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f8211a3a000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f8211820000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f8211603000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f82113db000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f82111a5000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f8210f33000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f8210d30000)
```
Thanks for help

**Comment by ZNixian** [comment]
Please excuse mind the warnings (for now, I plan to fix them), it's source code is directly based off the original PD2 hook which didn't pay much attention to warnings

**Comment by ZNixian** [comment]
For the latest version compiled on Ubuntu, check [the GitLab CI jobs page](https://gitlab.com/znixian/payday2-superblt/-/jobs) and download the latest (top) successful build's artefacts.

**Comment by ZNixian** [comment]
As of now SuperBLT has fully functional asset support, regardless of compiler ([commit that adds this, if someone wants to copy it to BLT4L](https://gitlab.com/znixian/payday2-superblt/commit/ff9d72e7bc6e80cf741ef9985eefbc6bf31d503e)).

This was (AFAIK) the last major thing BLT4L supported that SuperBLT didn't, so I'll close the issue.
